### ISSUE TITLE
Completely implement server side gumplings and client->server gump messages.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#100]
As part of the Milestone 0.5 roadmap, serverside gumps must be completely implemented. Substeps for this issue include XML gumplings and client->server gump messages.
- Many of the XML gumplings have not yet been implemented. Full support of serverside gumps will require implementation of these gumplings. 
- In addition, the client does not yet have the ability to 'post' messages to the server with serverside gumps (example: the search function in RunUO's [add menu). This should be implemented as well.

**Comment by ZaneDubya** [comment]
xmfhtmlgump and xmfhtmlgumpcolor gumplings introduced in branch server-side-gumplings.

**Comment by ZaneDubya** [comment]
Remaining to be implemented: group, endgroup, radio, checkbox, xmfhtmltok, tooltip.

**Comment by ZaneDubya** [comment]
Tooltip is implemented - I think - but I can't find anywhere in base RunUO where it is used.

Could someone locate examples where these gumplings are used? Preferably gumps in RunUO, so I can test them on my machine. :)
- group, endgroup, and radio
- checkbox
- xmfhtmltok
- tooltip

**Comment by fdsprod** [comment]
Stock RunUO doesnt use them.  Maybe a 3rd party script.

**Comment by fdsprod** [comment]
I did find that the default login screen has tooltips.  Lots of the UI that doesnt come from the server has tooltips.  Most of which are defined in Interface.def.

**Comment by robertdeclaux** [comment]
Sphereserver uses them but i still couldn't view gumps, trying to find out why it's not working.

**Comment by ZaneDubya** [comment]
xmfhtmltok implemented. Remaining controls are group, endgroup, radio, and checkbox.

**Comment by ZaneDubya** [comment]
checkbox implemented in d201c86da904d6d1f1b56564038e1943ca9a437a. Only radio and group/endgroup left!

**Comment by ZaneDubya** [comment]
radio, group, endgroup implemented in 4ab5f098bb947f395815c2246b0c4696822b3987. Closing as complete.
