### ISSUE TITLE
Milestone 0.5 Refactor

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#101]
As a maintainer of the codebase, I get jeebies every time I browse UltimaClient.cs. I'd like to better organize that file, partially by moving most of the world-modifying packets into a UltimaWorld.WorldClient.cs class.

I'd also like to fold BaseEngine and UltimaEngine into a single class.

Eliminate the extraneous Handlers in Core.Network.Client.cs (only need Typed Handlers).

Get rid of Point3D (not used throughout program).

Reorganize all the mouse picking code into a single class.

Rename UltimaGUI.Control to UltimaGUI.AControl (and make it abstract).

Move GUIManager to UltimaGUI namespace.

**Comment by ZaneDubya** [comment]
You can see my current progress on these goals in the branch Milestone0.5-Refactor.

**Comment by robertdeclaux** [comment]
It seems good on sphereserver without errors.

**Comment by ZaneDubya** [comment]
@robertdeclaux Thank you for confirming!
