### ISSUE TITLE
Could not find a Direct3D device that supports XNA Framework HiDef profile.

### ISSUE THREAD

**Issue by PatrikSamuelTauchim** [ZaneDubya/UltimaXNA#103]
Just getting this error in UltimaXNA console. Before that, I had to manually remove "InterXLib" from VS2010 solution, should I change something else or it's general issue?

Or should I switch to VS2013? :-)

**Comment by robertdeclaux** [comment]
My pc cannot load InterXLib, removing it solves problem too here.

**Comment by PatrikSamuelTauchim** [comment]
Yeah, I removed InterXLib and project got compiled, but after that, I am getting this error.

"Could not find a Direct3D device that supports XNA Framework HiDef profile."

**Comment by ZaneDubya** [comment]
Sorry about leaving the IXL reference in! I thought I had removed that. It should be removed from master now.

**Comment by ZaneDubya** [comment]
This problem arises due to the use of the new, larger hue texture. Other than the larger hue texture, there is no need for any of the 'HiDef' features.

**Comment by ZaneDubya** [comment]
I've implemented a new 'dual hue texture' strategy in the branch newhuing. In short, it splits the hues into two smaller textures, each of which barely fits the limit for a non-HiDef device. Would you check out that branch and see if it works for you? I'd check the hue debug screen (Ctrl-D at login) to make sure that things are still rendering correctly.

**Comment by PatrikSamuelTauchim** [comment]
Thanks, I got this output from newhuing branch.
![newhuing](https://cloud.githubusercontent.com/assets/11310587/7022328/523d3f9e-dd33-11e4-8b52-4341ee30d498.JPG)

**Comment by ZaneDubya** [comment]
Great! This is on the computer that had the "Could not find a Direct3D device that supports XNA Framework HiDef profile." error?

**Comment by PatrikSamuelTauchim** [comment]
Yes, my VM at work, where we also had issues with huing before. :-)

**Comment by ZaneDubya** [comment]
Cool! Thank you @Eskymak. Closed as fixed.
