### ISSUE TITLE
Connection lost message after logout

### ISSUE THREAD

**Issue by PatrikSamuelTauchim** [ZaneDubya/UltimaXNA#106]
After confirming logout using Logout button in Paperdoll, "You have lost your connection..." message is shown. To get back to login screen, you need to confirm this dialog.

**Comment by ZaneDubya** [comment]
Addressed in 857769652ab913a38337bdd7538c8fc742cf6da9.

**Comment by PatrikSamuelTauchim** [comment]
Confirm, Thanks!
