### ISSUE TITLE
Client hangs at "A character is already logged in"

### ISSUE THREAD

**Issue by PatrikSamuelTauchim** [ZaneDubya/UltimaXNA#109]
When another character from same account is already logged in and you trying to login with another one "A character is already logged in" dialog is show during login process. After confirming this dialog, client stays at "Entering Britannia..." screen.

Expected behavour is return to login screen.

**Comment by ZaneDubya** [comment]
Addressed in 1a9abce4cff865400c97022373b335a6e5c81422.

**Comment by PatrikSamuelTauchim** [comment]
Confirm, Thanks!
I guess, you can now also remove "using UltimaXNA.UltimaVars;" at line 16 in "PaperDollGump.cs". ;)

**Comment by ZaneDubya** [comment]
I guess so! And come to think of it, it might be time to consider getting rid of EngineVars altogether, since those variables should only be referenced/changed by WorldModel.
