### ISSUE TITLE
New refactor cannot opened by VS2010

### ISSUE THREAD

**Issue by robertdeclaux** [ZaneDubya/UltimaXNA#114]
"This project is incompatible with the current version of Visual Studio."
![3](https://cloud.githubusercontent.com/assets/11157985/7090554/7e930882-dfac-11e4-8d14-979b9126e551.PNG)

**Comment by fdsprod** [comment]
Just realized you said VS2010, Ya, you need VS2013, the express version will open it, you just need to follow the guide on the wiki.  The .net requirement moved to 4.5.  We arent certain any of these changes will make it to the master branch, we are discussing them for now.

**Comment by ZaneDubya** [comment]
Should be resolved in 5a33fa865a1cd7b9808df168bfeedd0e2abacda7 (current master). This is not to say that the .net requirement for master will not be raised in the future if we determine that features in .net 4.5 are too good to give up. :)

**Comment by robertdeclaux** [comment]
I forgot to try it again with .net 4.5, if its just because of that please move to .net 4.5 :)

**Comment by robertdeclaux** [comment]
I forgot to try it again with .net 4.5, if its just because of that please move to .net 4.5 :), (that was on my work pc tomorrow i will try)

**Comment by ZaneDubya** [comment]
I'm closing this as complete. Please reopen if it cannot be opened with VS2010.
