### ISSUE TITLE
Dragon (and may be other NPCs) has a spellbook anim

### ISSUE THREAD

**Issue by robertdeclaux** [ZaneDubya/UltimaXNA#118]
Minor error that occurs on sphereserver.
![ekran alintisi](https://cloud.githubusercontent.com/assets/11157985/7106923/06b9ee6a-e15b-11e4-835e-5dacec3bf1d0.PNG)

**Comment by ZaneDubya** [comment]
Haha, what's going on there? Does the Dragon have a spellbook equipped?

**Comment by robertdeclaux** [comment]
yes sphere handles it that epic way :)

**Comment by ZaneDubya** [comment]
This should be an easy fix: only draw equipped items for body ids that equate to humanoid mobiles.

Are humans 400 and 401? What are the other body ids?

**Comment by fdsprod** [comment]
mobile.IsHuman should be enough

public bool IsHuman { get { return m_BodyId == 400 || m_BodyId == 401; } }

**Comment by robertdeclaux** [comment]
I will check id tomorrow but gm body id needed too.

**Comment by robertdeclaux** [comment]
987 is the gm bodyid

**Comment by ZaneDubya** [comment]
What about elves and gargoyles? Not that gargoyles would work, because we don't support SA, but still ;)

**Comment by fdsprod** [comment]
https://github.com/runuo/runuo/blob/master/Server/Body.cs Heres everything you need ;)

EDIT: oh and this https://github.com/runuo/runuo/blob/master/Data/bodyTable.cfg

**Comment by ZaneDubya** [comment]
Nice! Thanks!

-Zane

**Comment by ZaneDubya** [comment]
Should be fixed! Merged into master. @robertdeclaux let me know if it's still not working.

**Comment by robertdeclaux** [comment]
It's working good.
