### ISSUE TITLE
Minimap rendering

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#121]
As a player, having a working minimap would really help me navigate the world.

As a first pass, the world could be displayed as a simple 2D texture. I imagine this would only take an hour to get running with ground only, and a few more hours would get statics/house multis displaying as well.

Can anyone answer these two questions regarding the legacy client's mini map view?
1. How does the game display a single tile in the 'slanted view' of the legacy minimap? What is the pixel pattern that is repeated? Is there a place in the game where we can see repeated features (a chessboard-like grid? Straight lines of tiles?).
2. I know that the legacy client uses a special graphic to draw trees. Where does it get this graphic from? Is there more than one kind of tree minimap graphic? Are there any other items that are drawn specially?

**Comment by robertdeclaux** [comment]
I'm not sure but it must be related with multimap.rle file

**Comment by Vodacek** [comment]
In this file are stored colors of pixels for minimap, I also think that every pixel corresponds to one tile on map
 
On minimap are also drawn multis (e.g. boat)
 

---

**Comment by fdsprod** [comment]
Radarcol.mul has the tile colors.  Its a lookup table m_RadarCol[tile.Id] or m_RadarCol[static.Id] As far as how to display the texture.  All you have to do is draw each pixel in relation to a tile x/y, then use something 
Matrix worldMatrix = Matrix.CreateTransform(textureWidth/2, textureHeight/2) \* Matrix.CreateFromAxisAngle(Vector3.UnitZ, 45) 
to get the rotation.  For things like houses, boats etc, you do the same lookup.  I do not believe multimap.rle is used.

I believe multimap.rle is used for cartographer stuff.

**Comment by ZaneDubya** [comment]
But wouldn't it be nice to be able to draw it pre-rotated? I'll bet it would look better that if it were rotated by the GPU.

**Comment by fdsprod** [comment]
It would not, you cannot do flush diagnol pixels that way.  Also, the texture would be 150% larger.  I'm 100% sure rotating it on the GPU will make it look exactly like the stock client.   They do the same thing, just in GDI

**Comment by ZaneDubya** [comment]
I'm not sure it would look exactly like the stock client...

There's a nice grid of tiles in Trinsic, which allowed me to play around with ways of drawing the tiles. In the legacy client minimap, the tiles are drawn as pairs (one on top of the other), with a x-stride of (+1, +1), and a y-stride of (-1, -1).

So then the only issue would be running out of space to draw the mini map on the texture as the client moves. We could either use four textures and switch around what data was drawn to each texture, or we could use just one texture and 'mirror' writes that would be outside the bounds of the minimap texture to the other side of the texture. The second would be the better solution, I think, if we could figure out what the appropriate size of the texture would be to 'mirror' properly (fitting an exact number of cells in with no overlap).

![map](https://cloud.githubusercontent.com/assets/7041719/7142826/e76a362c-e2a0-11e4-860a-06e0ed6b0f13.png)
![minimap-legacy](https://cloud.githubusercontent.com/assets/7041719/7142827/e77436d6-e2a0-11e4-85c0-3ec3aed3725e.png)

Each rotated cell of tiles (8x8) is 15x16px, so the texture wouldn't necessarily be a power of two.

**Comment by fdsprod** [comment]
Another way to do it would be to just draw a precalculated quad that is already rotated, this way you dont have to change shaders out.  

Something like:
var widthOver2 = width/2;
var heightOver2 = height/2

Vertex[] = new Vertex[4];

vertex[0].position = new Vector3(center.X, center.Y - heightOver2);
vertex[1].position = new Vector3(center.X + widthOver2 , center.Y);
vertex[2].position = new Vector3(center.X, center.Y + heightOver2);
vertex[3].position = new Vector3(center.X - widthOver2 , center.Y);

vertex[0].uv= new Vector2(0, 0);
vertex[1].uv= new Vector2(1, 0);
vertex[2].uv= new Vector2(0, 1);
vertex[3].uv= new Vector2(1, 1);

**Comment by fdsprod** [comment]
You need to only draw slighly out of view, lets say (20-40 pixels out of view in each direction), as they move you generate a new texture and swap it when they get close to an edge.  Dont draw the entire thing, or anything much larger than what they can see.

**Comment by ZaneDubya** [comment]
Next question - how could we mask the minimap texture so that only the portion within the center of the gump is drawn?

**Comment by fdsprod** [comment]
Also you need to set the texture sampler to TextureFilter.Point so it doesnt try to blend the pixels.

**Comment by fdsprod** [comment]
@ZaneDubya "Next question - how could we mask the minimap texture so that only the portion within the center of the gump is drawn?"

Ah right, So you need to draw a circle of vertices under the radar gump trim.  That's gonna be fun ;)
Or you can just create a black white texture mask and use it as the alpha channel in the shader.

**Comment by fdsprod** [comment]
On option 2, you could actually do all the masking work in the shader

Something like

float genMask(float2 uv, float radius)  // radius would be 0-1
{
    float dx = uv.x - 0.5f;
    float dy = uv.y - 0.5f;
    if(dx \* dx + dy \* dy <= radius)
        return 1;
    else
        return 0;
}

**Comment by ZaneDubya** [comment]
If each tile cell is 15x16px, then the visible areas of the two gumps are as follows:
Gump ID | Visible px | Visible cells
------------ | ------------- | -------------
5010       | 141x141   | 10x9
5011       | 198x197   | 14x13

Formatting is messed up, but you get the idea.

**Comment by ZaneDubya** [comment]
@jeffboulanger I like the radius idea. Would it be possible though to use the properties of the minimap texture to mask it though? The masking color in the gump is always 0x080808.

**Comment by fdsprod** [comment]
Ya given that, 0x080808 = 1, anything else = 0

**Comment by ZaneDubya** [comment]
A 256x240 pixel texture would hold exactly 16x16 cells, and would be more than big enough to fit either minimap gump. We could determine which cells needed to be 'mirrored' (or drawn on both sides) with a quick modulus 16.

**Comment by fdsprod** [comment]
Sounds good, just dont generate it everytime they move ;) Only if the next step (or 2) will put a border on the radar.

**Comment by fdsprod** [comment]
A better thing to do would be to start a pre-cache of the next texture on a secondary thread when they are getting close, but that's obviously a lot more complex.

**Comment by fdsprod** [comment]
A nice to have would be smooth minimap movement as well.

**Comment by ZaneDubya** [comment]
Is it possible to make it smoother than the legacy client?

AFAIK, it always moves one-two pixels per tile moved. What makes it rough and lurching is the slow and granular nature of movement in UO: one tile moved every 100-400ms. It makes sense that an image updating 2.5x a second would seem jerky.

**Comment by fdsprod** [comment]
ya you could just have it move smooth based on player position between tiles.  Movement becomes a pixel ratio of the distance the player is between the tile.

**Comment by ZaneDubya** [comment]
So we would be placing the minimap texture at non-integer positions, which would cause the texels of the minimap picture to be blurred between different screen pixels - but only when it was moving, of course, so it would still look sharp when the player wasn't moving. That's a good idea.

**Comment by fdsprod** [comment]
Might be worth a look, if its terrible, then don't do it, but should be easy to try. We can just do a post process motion blur on it while moving, haha, That would look amazing!

**Comment by ZaneDubya** [comment]
Yeah, it would be super simple to do!

My one remaining question is how to do the masking.

Here's what I'm thinking: 
- Load the minimap data texture permanently into one of the texture units, just like we load the hue textures so they're always available.
- When we render the minimap gump, we put the correct offset for the minimap data texture in the Extra element in the gump's VertexPositionTextureHueExtra vertexes.
- In the shader, replace all instances of 0x080808 with the texels from the data texture. We'll set TextureFilter to Linear for this operation.

**Comment by fdsprod** [comment]
Why do you need hues?

**Comment by ZaneDubya** [comment]
The hue textures always occupy two texture units. I'm saying the minimap texture should likewise occupy one texture unit. Then we would have four textures loaded: the currently rendered texture (could be a gump or a aim or anything), the two hue textures, and the minimap data texture.

**Comment by fdsprod** [comment]
Not sure I follow, I'd have to look at the code.

**Comment by fdsprod** [comment]
Oh I think I understand.  So do you always send the textures even if they arent used?  Super inefficient :( 

You should create multiple functions in the shader, change the pass name so that you only execute code based on the needs for the item/static/gump/etc,  Sending the hue for Gumps means that each draw call that the shader executes on the texture is passed to the graphics card, this is one of the most intensive operations (especially for large textures) you can do.

**Comment by ZaneDubya** [comment]
The hue textures are set just once. Sorry I didn't make that clear. Obviously the currently rendering texture (the gump, for example) changes for each time a new batch of objects are drawn. The minimap texture would only be reset when it is updated.

**Comment by fdsprod** [comment]
Setting them 1 time doesnt mean its efficient, they are still sent to the GPU even when not in use.  Setting them in code just tells the Effect that the resource is going to be needed by the GPU, so when the Draw calls sent to the GraphicsCard, internally the GPU receives the Texture from memory.   You shouldn't set the texture, unless its required by the Draw call.

**Comment by ZaneDubya** [comment]
They're only sent to the GPU from memory when they are assigned with `GraphicsDevice.Textures[i] = texture;` Thus, the hue textures are assigned and sent once, and this occurs after they are generated in UltimaEngine. Unassigning and reassigning the textures would cause a performance hit; leaving the textures assigned will not. I think you and I may be misunderstanding each other.

**Comment by fdsprod** [comment]
I see what you are saying, I misunderstood.  However your statement isnt true when you have limitted GPU memory or lots of textures.  XNA tries to store everything on the GPU but will pull it into memory when not used to free up resources.  In the cases above, thats probably not happening.

**Comment by ZaneDubya** [comment]
Can't help myself, starting this now :)

**Comment by ZaneDubya** [comment]
Minimap is ready for QA in branch MiniMap. Please test to see if it's working.

Note that I do not expect the minimap's output to match the legacy client's exactly. There will be some tiles that are incorrectly colored. I believe this has to do with the XNA client's drawing some statics that are not drawn in the legacy client's minimap. Specific instances of mismatched tiles should be noted in a separate "bug" issue.

**Comment by fdsprod** [comment]
Looks jumpy, can't you pass in an offset to the shader based on how far the player is between tiles, then use that divided by the number of pixels w/h to determine where the player is between a minimap pixel.  Then apply that result to IN.Normal.xy to render smoothly?

**Comment by ZaneDubya** [comment]
Yes, I can, but it won't do anything to the texture unless we use texture filtering, which will make the minimap texture blurry.

You can try this yourself: in SpriteBatch3D.cs, set GraphicsDevice.SamplerStates[3] to SamplerState.AnisotropicWrap.

Then remove the two calls to Math.Round in MiniMap.cs. Voila.

**Comment by ZaneDubya** [comment]
On another note entirely...

So you'll notice that walls and roofs look ever so slightly off compared to legacy. This is because the legacy minimap actually takes elevation into account!! How cool is that. Not sure I want to spend the time replicating that, though ;)

**Comment by robertdeclaux** [comment]
Mine overview seems blank with just blinking white dot, on intel hd4000 graphics.

**Comment by ZaneDubya** [comment]
@robertdeclaux Okay, that means that at least I've managed to switch over the shader in SpriteBatch3D! So either the shader isn't working or the texture isn't being written to or the texture isn't being assigned to the GPU. Could you download the latest commit and try opening the 'debug' gump from the top menu? The entire minimap texture should be displayed in that gump, using the standard HueTechnique that is used for every other draw call in the game.

**Comment by ZaneDubya** [comment]
@robertdeclaux's problem is fixed in #122. Merged. Let me know if there are any additional issues.

**Comment by robertdeclaux** [comment]
It works great without any problem.
