### ISSUE TITLE
Death effect and hue world in grayscale when dead.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#125]
As a player, I want to see the soul-crushing death effect when I die: A fade to black, followed by the sad realization that I am dead, and all the color has been drained from the world.

**Comment by ZaneDubya** [comment]
I wonder how much work this will be! Could be easy, could be hard...

**Comment by fdsprod** [comment]
@ZaneDubya an easy way would be to do it in a shader, changes nothing else

```
float greyscaleAverage = (color.r + color.g + color.b)/3.0f;
Output.Colour = float4(greyscaleAverage, greyscaleAverage, greyscaleAverage, trueColour.a);
```

or alternate way to do it

```
float greyscaleAverage = (byte)round(0.2989 * color.r + 0.5870 * color.g + 0.1140 * color.b);
Output.Colour = float4(greyscaleAverage, greyscaleAverage, greyscaleAverage, trueColour.a);
```

**Comment by ZaneDubya** [comment]
Thanks!

I'm also going to need to add the fade to black effect, the 'you are dead' pop up, and resurrect menu handling.

**Comment by ZaneDubya** [comment]
Off to a good start ;)

![screen shot 2015-06-07 at 10 37 54 am](https://cloud.githubusercontent.com/assets/7041719/8024669/4bed1436-0d01-11e5-96cd-6674ddaaf1b2.png)

**Comment by ZaneDubya** [comment]
That's more like it!

![screen shot 2015-06-07 at 10 44 28 am](https://cloud.githubusercontent.com/assets/7041719/8024689/48657a5a-0d02-11e5-8e67-1d6d5c2cff17.png)

**Comment by naggie** [comment]
very nice!

**Comment by ZaneDubya** [comment]
Thanks @naggie!

As of 9a4671a, death effect is complete.

**Comment by PatrikSamuelTauchim** [comment]
Character created in UltimaXNA is dead after creation. After that, it is ressurected. Just for me?

**Comment by ZaneDubya** [comment]
Darn. This was an issue some time ago. I thought I had fixed it. Obviously, need a better fix... 

Open a new issue for this bug, and I will do some bug testing later this week.

**Comment by fdsprod** [comment]
@ZaneDubya Just so you know, the characters ghost and I believe other ghosts are rendered in color (hands and feet are skin color) when dead

**Comment by ZaneDubya** [comment]
@jeffboulanger  Huh - do you think that's a deliberate choice by the developers?
