### ISSUE TITLE
Restrict gumps from moving off screen.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#127]
As a player, I can, with one misplaced drag of the mouse, move a gump entirely off screen. I've now lost a paperdoll, and can't close it. Oops.

I believe it would be appropriate to stop gumps moving off the screen either entirely, or when only a portion of the gump (1/2?) remains on screen.

**Comment by robertdeclaux** [comment]
That would be great :+1:

**Comment by fdsprod** [comment]
I believe the original client lets you do this, and I thought that when you either open it again, it fixes it, or there was a hot key that fixed it.

**Comment by ZaneDubya** [comment]
I don't like the possibility of 'losing' gumps. I can think of four potential fixes:
1. Restrict gumps from moving off-screen, either in their entirety, or by stopping them when they are 'half off' by width.
2. Clip mouse move messages to the client window when sent to the UI.
3. Clip the mouse to the client window when a button is down.
4. Indicate with an arrow message when gumps are off screen.

Honestly, I like just restricting gumps from moving off screen. You can put them 'halfway' off, but they won't go further.

As a side note, it's also possible to expand a scroll to be larger than the screen. That should be restricted in some way as well ;)

**Comment by fdsprod** [comment]
I wouldnt do 1/2 the gump allowed off screen,  I would allow 90%, having have the gump cover my screen at all types, would drive me crazy.  Especially since UltimaXNA doesnt correctly show the game window gump yet.

**Comment by PatrikSamuelTauchim** [comment]
@jeffboulanger If you allow 90% of the gump to be off screen, It can happen that some gump wont be visible at all, because some gumps are transparent at borders and it could be 10% of it. Journal for example. Black space around world view is real need.

**Comment by fdsprod** [comment]
@Eskymak  90% was relative, it can be adjusted, we could also create a bounding box based on non transparent pixels, and use it's 90% to determine how far off the screen it should go.

**Comment by ZaneDubya** [comment]
I think that 50% would be good _if_ the game window gump worked correctly.

**Comment by Vodacek** [comment]
I agree 50% sounds good :-)

**Comment by PatrikSamuelTauchim** [comment]
:+1:  for 50% (can be changed anytime anyway) :-)

**Comment by ZaneDubya** [comment]
Implemented in f4aeb0fb812910ae4c963fc9a6e853a3ca9b47e2.
