### ISSUE TITLE
Only half of speech imput line shows text entered

### ISSUE THREAD

**Issue by PatrikSamuelTauchim** [ZaneDubya/UltimaXNA#129]
When typing into speech imput line (at the bottom of window), text entered is visible only at first half of the line and if longer than 50%, it ends with "-" for some reason. Over head text is shown correctly.

**Comment by ZaneDubya** [comment]
Two questions regarding this issue - may have the same answer:
- What is the maximum length of chat message that the legacy client allows to be entered?
- What is the maximum length of chat message that RunUO will accept?

**Comment by Vodacek** [comment]
according to RunUO core source:

```
if ( text.Length <= 0 || text.Length > 128 )
return;
```

Packet 0x03 in method AsciiSpeech

**Comment by ZaneDubya** [comment]
Thanks @Vodacek.

Two things need to be done then: limiting the text entered in the chat window to 128 characters, and scroll the text so that it doesn't overflow the textbox (which, I think, is what is causing @Eskymak's issue).

**Comment by ZaneDubya** [comment]
In 9b2af66, the max chat text length is 96, and the text now scrolls.
