### ISSUE TITLE
Remember last position of gumps

### ISSUE THREAD

**Issue by PatrikSamuelTauchim** [ZaneDubya/UltimaXNA#131]
For gumps like backpack, topmenu, journal, paperdoll and so on, we expected to remember last position to be opened at next time.

**Comment by ZaneDubya** [comment]
This should be an easy addition...

**Comment by ZaneDubya** [comment]
Implemented in bc060f0.

**Comment by PatrikSamuelTauchim** [comment]
Thanks, seems it works. It will get more serious testing during normal usage. :-)
Could we also get automatic reopening of last (before logout) opened gumps, after login?

**Comment by ZaneDubya** [comment]
@Eskymak opened your suggestion as a new feature: #163.
