### ISSUE TITLE
World Rendering Gump

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#132]
Once #39 is complete, UltimaXNA will have a large client window, but the world view would unmoveable and unloveable in the top-left. @Eskymak and @jeffboulanger are right: the world rendering gump is a must.

**Comment by ZaneDubya** [comment]
Implemented in branch vodacek-windowing. You should be able to move the window, and mouse input should work exactly like the legacy client. Requesting QA.

**Comment by ZaneDubya** [comment]
![screen-shot-2015-04-22-at-10 31 08-am](https://cloud.githubusercontent.com/assets/7041719/7278450/2eaba3be-e8db-11e4-9b51-ecbfdf69ead9.jpg)

**Comment by robertdeclaux** [comment]
World rendering gump works without any problems :+1: , I'm not sure what triggered it but just skills gump has some problem with scrollbar. Only difference between default client, when client launched it starts on centered not on the top left.
