### ISSUE TITLE
Complete Paperdoll gump

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#135]
Paperdoll gumps need titles, and (potentially) the various scrolls on the side.

**Comment by ZaneDubya** [comment]
Issues:
- [x] Peace/War button does not change color.
- [x] No hat/earings/neck/ring/bracelet slots.
- [x] No character name/title/skill.
- [x] Guild button non-functional (who uses this?)
- [x] Quest button non-functional (who uses this?)
- [x] Log out prompt poorly sized.
- [x] Options button non-functional.
- [x] Help button non-functional (who uses this?)
- [x] Virtue menu non-functional (who uses this?)

**Comment by PatrikSamuelTauchim** [comment]
Regarding "who uses this?", in combination with gumpart modification, you can simply change look of those buttons and use them for whatever you want. :-)

**Comment by ZaneDubya** [comment]
@Eskymak Haha, do you have any suggestions?

**Comment by PatrikSamuelTauchim** [comment]
@ZaneDubya Those buttons probably just sending "I was pressed" packet and then is up to server what will happen (some custom gump/action or nothing). Not sure if all "who uses this?" buttons behave like this. @Vodacek would know better.

I actually see priority in Options gump, but since we have no tool to design gumps, it is quite challenging to make stuff like this.

**Comment by Vodacek** [comment]
Sure I know :-) All these buttons (help, guild, quest...) sends message to server. I will find the packets when I arrive at home.

**Comment by ZaneDubya** [comment]
Great! Thanks :)

**Comment by Vodacek** [comment]
packet 0x34 subcommand 0x5 for skills button (https://github.com/runuo/runuo/blob/master/Server/Network/PacketHandlers.cs#L102 and https://github.com/runuo/runuo/blob/master/Server/Network/PacketHandlers.cs#L1955)
packet 0x32 for quest button (https://github.com/runuo/runuo/blob/master/Server/Network/PacketHandlers.cs#L177 and https://github.com/runuo/runuo/blob/master/Server/Network/PacketHandlers.cs#L288)
packet 0xB5 for chat button (https://github.com/runuo/runuo/blob/master/Scripts/Engines/Chat/Chat.cs)
packet 0x9B for help button (https://github.com/runuo/runuo/blob/master/Server/Network/PacketHandlers.cs#L125 and https://github.com/runuo/runuo/blob/master/Server/Network/PacketHandlers.cs#L1096)

**Comment by ZaneDubya** [comment]
Options button functionality was added by @Eskymak. Thanks!

**Comment by ZaneDubya** [comment]
So --- under what conditions is the Special Moves book available?

**Comment by ZaneDubya** [comment]
Ugh, looks like the special moves book is a local gump, like the spellbook. I do not want to have to do another one of those, haha.

**Comment by ZaneDubya** [comment]
Moving 'Special Moves' functionality to Milestone 0.7 / Issue #217

**Comment by ZaneDubya** [comment]
Profile and Party Menu scrolls are also clientside. Ugh, you know what, I'm going to defer doing these as well. They're not critical functionality.

**Comment by ZaneDubya** [comment]
Closing as implemented.
