### ISSUE TITLE
Single-left-click context menus.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#139]
I remember there were context-menus in Ultima Online, though I can't remember what entities did or did not have them. I think this might be a server-side thing: when the server detects a single left-click on an object, it sends a context-menu if one exists. If one doesn't exist, then nothing happens server-side on a single click. Please correct me if I'm wrong.

In any case, when the client receives a context menu packet from the server, display a context menu for that entity. Only one context menu should be visible at a time.

This will also require implementing the context menu response packet.
![context](https://cloud.githubusercontent.com/assets/7041719/7372661/a874c2dc-ed8d-11e4-8bc2-afba2e6d6124.jpg)

**Comment by naggie** [comment]
For example, right-clicking on a skittering hopper -> tame?

**Comment by ZaneDubya** [comment]
Yes! But is it single left click or right clicking?

**Comment by PatrikSamuelTauchim** [comment]
@ZaneDubya Single left click for context menu on items and mobiles.

**Comment by ZaneDubya** [comment]
Off to a good start!
<img width="516" alt="context" src="https://cloud.githubusercontent.com/assets/7041719/8890090/3fc89de6-32b9-11e5-8560-c1e154da6aa6.png">

**Comment by robertdeclaux** [comment]
is it the footsteps of buy/sell menus :+1:

**Comment by robertdeclaux** [comment]
:+1: sounds like buy/sell menus are coming

**Comment by ZaneDubya** [comment]
Implemented in #229. Closing as implemented.
