### ISSUE TITLE
Add support for client chat commands.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#140]
The legacy client transmits 'chat commands' when it recognizes certain words in player-sent chat messages ('bank', 'guards' 'vendor sell' 'all stop', etc.). These commands are sent as integer indexes, based on (I think?) some limited subset of the cliloc tables.

**Comment by Vodacek** [comment]
In UO packet guide I have this:

```
0x0000 *withdrawal *
0x0001 *balance*
0x0001 *statement*
0x0002 *bank*
0x0003 *check *
0x0004 *join*
0x0004 *member*
0x0005 *quit*
0x0006 *resign*
0x0007 *guild*
………………
```

for all of them see speech.mul ;)

**Comment by ZaneDubya** [comment]
Nice! Thanks :)

**Comment by Vodacek** [comment]
@ZaneDubya  you are welcome!

**Comment by ZaneDubya** [comment]
Hmm. It's working again... no idea when or why it started working. Closed.
