### ISSUE TITLE
Pop-up item properties

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#141]
Some items (and potentially other objects?) have properties, which display in a window on mouse-over. This should be implemented!

![insurance3](https://cloud.githubusercontent.com/assets/7041719/7409880/9fb7e094-eeef-11e4-9bf2-07cc78c4f908.jpg)

**Comment by Vodacek** [comment]
items, mobiles can have this, in RunUO these properties can be added by overriding:

```
public override void GetProperties(ObjectPropertyList list)
{
    base.GetProperties(list);
    list.Add("some string");
    list.Add(108468);//cliloc? int
}
```

Some have also variable parametres. For strings (first case) ~1_NOTHING~ (cliloc id 1042971) is replaced by string. In this text can be used HTML to change color and so on :-) We use this at our shard a lot and it would be great to have it!

**Comment by fdsprod** [comment]
Creating that repeating transparent mesh texture is simple as 4x4 tiled texture:
black,               tranparent, 
transparent,     black
Then just tile when you draw.  Now that the world view is inside a gump this can actually be implemented for regular gump transparencies.   Last I checked this was not complete (granted its been a bit)

**Comment by ZaneDubya** [comment]
Nice point jeff. Transparent gumps are a definite must-have feature.

**Comment by ZaneDubya** [comment]
Only items can have tooltips, right? Not mobiles.

**Comment by PatrikSamuelTauchim** [comment]
@ZaneDubya  Mobiles also showing more than name, when you hoover mouse over them, tame status for example.

**Comment by ZaneDubya** [comment]
Hm. One more thing to do. ;) Thanks @Eskymak.

I have very basic item properties displaying! Not in color yet, and the tooltip is not yet correctly sized, but it's a start!

**Comment by ZaneDubya** [comment]
Tooltips are now correctly sized. Two things remain to do:
1. Capitalize beginning of each line of an item tooltip.
2. Color the item name (when is this done?)
  2a. This is very likely done in the GetProperties method which @Vodacek has highlighted. Some sleuthing is necessary to determine under what conditions an item's name is changed to a different color.

**Comment by ZaneDubya** [comment]
Capitalization implemented.
Still curious as to when the name of an item is colored...

**Comment by ZaneDubya** [comment]
Answer: always. Every object I've seen is hued kinda yellow.

**Comment by ZaneDubya** [comment]
Completed in 10430f88a679147a1fb5d78dd6da64b44b790fcd.

**Comment by naggie** [comment]
:+1: How about a screenshot?

**Comment by ZaneDubya** [comment]
@naggie A little blurry (I haven't yet figured out how to resize to 50% from the command line using anything but sips' default algorithm), but still shows what has been accomplished:
<img width="516" alt="ss" src="https://cloud.githubusercontent.com/assets/7041719/8995632/5f5b61e8-36d8-11e5-962d-ce5a3ac3ca23.png">

**Comment by naggie** [comment]
Very nice! Looks like the client is on its way to feature parity.

**Comment by ZaneDubya** [comment]
@naggie Haha some day! :)
