### ISSUE TITLE
Correct display of equipped candle object.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#142]
For whatever reason, candles are not displaying correctly when held as equipment. When equipped and the mobile is moving, they don't move as other equipment does; instead, they remain stationary.

**Comment by PatrikSamuelTauchim** [comment]
Same for lantern, and maybe for other light sources.

**Comment by ZaneDubya** [comment]
So... it looks like the candle animation has only one frame! What's up with that?

**Comment by ZaneDubya** [comment]
So there are definitely candle graphics! I wrote a debugger that extracted 1457 frames of candle animations (and one buggy null frame: action 13, direction 4, frame 3). Makes one realize how much detail Ultima Online contains. I'm forever impressed by the developers and artists of the same.

However, these graphics aren't being loaded by the game! I'm not entirely certain why this might be the case - and why it only happens with candles and lanterns. Perhaps there's a bug in MobileAnimation.cs? Perhaps it has something to do with the item being held in the off-hand?

The mystery continues.

**Comment by ZaneDubya** [comment]
Ugh. 2 minutes with InsideUO showed the solution to the problem: when a mobile is moving while carrying a light source, it should use the Armed action indexes, not Unarmed. This should be a five minute fix. I've spent hours on it.

**Comment by ZaneDubya** [comment]
As an aside, the 'stand unarmed' and 'run unarmed' animations are fully animated, but stationary, as if they were meant to be displayed while the mobile is standing still. I wonder why this is.

**Comment by ZaneDubya** [comment]
Oh dear god. If there's a contest for worst coded class in UltimaXNA, MobileAnimations.cs is certainly in the running. It was the first c# class that I wrote after getting login working (jeff will attest to how much of a travesty login was and - in the master branch, at least - remains). It's a horrifyingly complex spiderweb of code and cruft.

**Comment by naggie** [comment]
ha. And what's the best class?

>  Makes one realize how much detail Ultima Online contains
> Part of the reason ultima is so great!

 No wonder the introduction of KR graphics was not well received. Pixel art!

**Comment by ZaneDubya** [comment]
@naggie Whichever class I've written most recently is what I'd call the best!

And I'm 100% in agreement with you! Warts and all, I love the classic client's graphics. Pre-LBR, of course. :wink:

**Comment by ZaneDubya** [comment]
Closing as complete.
