### ISSUE TITLE
Mobiles sit when their position, including z-offset, matches an object which can be sat upon.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#144]
As a player, seeing a mobile 'sit' is a nice visual effect. I'd like to see this implemented!

Critical questions for this issue:
- Which item ids can be sat upon? Is this an item flag?
- Which mobiles can sit? Only humanoids, I assume?
- How does the legacy client transform sprites that sit?
- How can we implement this is UltimaXNA?

**Comment by PatrikSamuelTauchim** [comment]
- List of items on which you can sit is probably hardcoded in legacy client. No flag in tiledata for that as far I know.
- Yep, probably only humanids can sit
- 
- Would be nice to have external file with item IDs defined - much better then hardcoded list.

**Comment by ZaneDubya** [comment]
Let's do this!

**Comment by ZaneDubya** [comment]
It seems that Unknown4 is a height offset for the sitting mobile. Good to know.
