### ISSUE TITLE
Disconnecting due to inactivity...

### ISSUE THREAD

**Issue by PatrikSamuelTauchim** [ZaneDubya/UltimaXNA#156]
After few minutes of running UltimaXNA without any activity, runuo is disconnecting player due to inactivity. It does not happen with classic client.

Does classic client uses some kind of keep alive?

**Comment by Vodacek** [comment]
I think that server sends some packet and client allways responds if not, RunUO disconnects the client.

**Comment by fdsprod** [comment]
I dont think the client listens for this packet anymore, hasn't for a long time.  It should just be removed from UltimaXNA

**Comment by ZaneDubya** [comment]
There is a heartbeat packet. I've seen it before - perhaps one of the 0xBF packets?

**Comment by ZaneDubya** [comment]
This might be it. [Polserver packet guide](http://docs.polserver.com/packets/index.php?Packet=0xBF) says that the use of the 0xBF/0x24 packet is unknown. What does RunUO do with this packet?

11:31:26.0784: Client -> Server 0xBF (Length: 6)
        0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
       -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
0000   BF 00 06 00 24 48                                  ....$H

11:31:28.9940: Client -> Server 0xBF (Length: 6)
        0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
       -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
0000   BF 00 06 00 24 6B                                  ....$k

11:31:33.2408: Client -> Server 0xBF (Length: 6)
        0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
       -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
0000   BF 00 06 00 24 55                                  ....$U

11:31:36.8385: Client -> Server 0xBF (Length: 6)
        0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
       -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
0000   BF 00 06 00 24 28                                  ....$(

11:31:40.9833: Client -> Server 0xBF (Length: 6)
        0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
       -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
0000   BF 00 06 00 24 5A                                  ....$Z

11:31:44.4459: Client -> Server 0xBF (Length: 6)
        0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
       -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
0000   BF 00 06 00 24 49                                  ....$I

11:31:48.3837: Client -> Server 0xBF (Length: 6)
        0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
       -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
0000   BF 00 06 00 24 58                                  ....$X

11:31:53.0436: Client -> Server 0xBF (Length: 6)
        0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
       -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
0000   BF 00 06 00 24 51                                  ....$Q

11:31:56.7193: Client -> Server 0xBF (Length: 6)
        0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
       -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
0000   BF 00 06 00 24 45                                  ....$E

11:32:00.4980: Client -> Server 0xBF (Length: 6)
        0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
       -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
0000   BF 00 06 00 24 2A                                  ....$*

**Comment by Vodacek** [comment]
I found in RunUO source this: https://github.com/runuo/runuo/blob/master/Server/Network/PacketHandlers.cs#L170 and handler is empty: https://github.com/runuo/runuo/blob/master/Server/Network/PacketHandlers.cs#L272 so, this solution should work well :)

**Comment by ZaneDubya** [comment]
Thanks for looking that up! I'm going to close this as fixed.
