### ISSUE TITLE
Spell effects displayed in the world.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#16]
The client does not yet support the built-in UO particle effects, which are 
used for spells (amongst other things). The client should be able to support 
these.

An easy way to generate a particle effect as a test is to use the [tele 
command on RunUO: this will generate a cloudy effect at both your start and 
destination location.

**Comment by ZaneDubya** [comment]
Finished in commit 8a9ca2145ad1ad6381c45085fe5c27833b4f63be.

These effects will work:
Any effect that is stationary (the [tele effect, for example).
The lightning spell effect.

These effects are not implemented:
Any effect that creates a moving object (the fireball spell, for example).

Would someone be willing to test out different spells to see if they're working, and report back on any bugs you find?

**Comment by robertdeclaux** [comment]
I will do but i don't have compiler or uo files now

**Comment by ZaneDubya** [comment]
Thanks!

**Comment by robertdeclaux** [comment]
On my server (no necromancy, or other new skills supported) teleport effect, lightning effect working correctly.
I'm not sure but i remember this spells as non-moving animations but currently they are not displayed on my server: 
Nightsight, Weaken, Agility, Cunning, Cure, Harm, Bless, Magic Reflection.

But may be there is another problem with targetting, i'm casting paralyze, i target on horse, cursor changed to default and no animation, no freeze. Then again i'm casting paralyze it says targetting canceled.
![ekran goruntusu 35](https://cloud.githubusercontent.com/assets/11157985/6891499/65cd717a-d6c4-11e4-964b-23537ad3ee6f.png)

**Comment by ZaneDubya** [comment]
Thank you @robertdeclaux . I'll take another pass at it.

**Comment by ZaneDubya** [comment]
All of those spells work on ML/RunUO 2.2.

**Comment by ZaneDubya** [comment]
@robertdeclaux 

All of those spells display on my end, using data from ML, server is RunUO 2.2. I wonder what's causing them not to display on your server. Paralyze also works on my server. No graphical effect (nor is one intended to be displayed, based on my reading of Paralyze.cs) , but I can hear the sound effect, and my mobile does get paralyzed if my eval int is high enough. :)

**Comment by robertdeclaux** [comment]
After fixing the target bug(https://github.com/ZaneDubya/UltimaXNA/commit/acb350bfcf60f5cba13132672f0c9727a41d33ee), it runs as you described. (on sphereserver too)

**Comment by ZaneDubya** [comment]
Nice! Thank you for checking! :)

**Comment by ZaneDubya** [comment]
@robertdeclaux  Are the graphical effects still not displaying when you use the XNA client? I wonder why that could be... Maybe I'm not handling part of the packet protocol?

**Comment by robertdeclaux** [comment]
Paralayze, lightning, night sight, weaken, reactive armor, cunning, harm, bless, magic reflection this all tested and displaying effects, i think all of it working.

**Comment by ZaneDubya** [comment]
Closing then. Thank you!
