### ISSUE TITLE
Items should be hued yellow on mouseover

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#162]
Picking up very small objects - a coin, or gem, for example - can be difficult. One way the legacy client makes this easier to achieve is by huing the object the mouse is over with a sort of off-yellow color. The XNA client should implement this as well.

**Comment by Vodacek** [comment]
There is flag in Tile data for that. When the weight is set to 255 and item is movable false object is not changing hue if mouse is over.

**Comment by ZaneDubya** [comment]
I've taken a first shot at this highlighting - should work in inventory, and on ground, and no where else. Like the legacy client (I think) frozen objects (items that are dynamic, but sent from the server) still highlight, but you cannot pick them up.

**Comment by PatrikSamuelTauchim** [comment]
@ZaneDubya Works fine, just color is little bit off.

**Comment by ZaneDubya** [comment]
@Eskymak Thanks for checking! I wonder what the correct hue is...

**Comment by ZaneDubya** [comment]
Okay, it looks better. Not perfect, but better. :)
