### ISSUE TITLE
Footstep enhancements

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#167]
1. Volume is too loud.
2. UO client varies pitch of footsteps to give the sound effects a little more variety.
3. Should volume be reduced - slightly - for mobiles that are not onscreen?

**Comment by PatrikSamuelTauchim** [comment]
@ZaneDubya 
- We could place volume value into settings. And also create separate volume value just for footsteps, to allow player adjust or disable footstep sound. If there is too many mobiles around, footsteps are just annoying.
- What about volume, that will depend on distance of the mobile from centrer of screen (player character)?

**Comment by ZaneDubya** [comment]
I've also noticed that now every mobile has footsteps. Orcs... dogs... birds. Aren't there alternate noises for animals? Or do they not make footstep noises at all?

**Comment by fdsprod** [comment]
I think just Humanoids

**Comment by ZaneDubya** [comment]
Ok, implemented all of these. Merging.
