### ISSUE TITLE
Better selection of small objects.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#17]
What steps will reproduce the problem?
1. Put some small object or object with transparent pixels on the ground (e.g. black pearl or spider silk)
2. Try to pick it up.
3. Fail.

What is the expected output? What do you see instead?
- Objects should be easier to pick up from the world.

**Comment by PatrikSamuelTauchim** [comment]
Show "something" above items? Original client does that while pressing ctrl + shift key combination.

**Comment by ZaneDubya** [comment]
I like that idea. Created separate issue #19 for "Show all" key combination.

**Comment by ZaneDubya** [comment]
Problem: Currently, you can only select an item if your mouse cursor is above a non-transparent pixel. Thus, any item with transparent pixels spread throughout the image, AND items that are narrow, are difficult to select.

Solution: Perhaps allow selection if there is a non-transparent pixel below the mouse cursor or at an offset of (-1,0), (0,-1), (1,0), or (1,1). This will allow selection even when the mouse cursor is directly over a transparent pixel, and will also increase the 'selection space' of an item by one pixel in each dimension - thus a very thin object (2-3 pixels wide) will be increased.

**Comment by ZaneDubya** [comment]
This code should be implemented in ItemGumpling.m_HitTest (this routine should also be renamed; it is not a variable).

**Comment by ZaneDubya** [comment]
Addressed in PR #48: Better selection of small objects.
