### ISSUE TITLE
GUI should ignore brackets when entered by the player in a textbox.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#18]
What steps will reproduce the problem?
1. Type 'Hello<small>world' in the chat box.

What is the expected output? What do you see instead?
In most if not all situations, the player should not be able to enter HTML code. We should always escape html characters that have been entered by the user.

**Comment by ZaneDubya** [comment]
Okay! Added escaped characters in bb73891b92a1d2a7ae0731261a1b351c9a23a6dd.

**Comment by robertdeclaux** [comment]
confirmed.

**Comment by ZaneDubya** [comment]
Thanks @robertdeclaux !
