### ISSUE TITLE
Join the Gitter chatroom!

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#187]
I've started a chatroom for UltimaXNA using Gitter. If you have any questions about UltimaXNA, join us there! [![Join the chat at https://gitter.im/ZaneDubya/UltimaXNA](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/ZaneDubya/UltimaXNA?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by ZaneDubya** [comment]
I think I killed gitter :(

**Comment by fdsprod** [comment]
?

**Comment by ZaneDubya** [comment]
I added and then deleted gitter permissions in rapid succession - whereafter I couldn't enter the gitter chatroom. Seems to be working now.
