### ISSUE TITLE
Player names not sent correctly on RunUO 2.4

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#194]
Creating a player on RunUO 2.4 leaves the player with the name 'Generic Player'

**Comment by fdsprod** [comment]
Just  an FYI on this, 2.4 has issues, big bugs.  I would try on a previous version.

**Comment by ZaneDubya** [comment]
@jeffboulanger Confirmed - it works on 2.0 and 2.3. And on 2.4.1. In fact, I can't get it to replicate on 2.4.0 :disappointed: I'm closing this as unreproducible.
