### ISSUE TITLE
AsciiFonts and UniFonts should be one kind of resource.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#200]
Right now, UXNA treats AsciiFont resources and UnicodeFont resources as different entities. The legacy client seems to treat them the same way: ascii fonts are used in the user interface but not in server side gumps or html, which almost exclusively use ascii fonts.

But there's no real reason for this separation. Why shouldn't AsciiFonts and Unicode fonts be utilized the same way? Why shouldn't a html gump use ascii fonts?

**Comment by fdsprod** [comment]
Because Unicode fonts have a larger characterset and respect localization, ascii fonts do not.  You should treat them separately or always use Unicode.  ASCII is used in servers trying to recreate older times in uo prior to UOR

**Comment by ZaneDubya** [comment]
@jeffboulanger I meant that they should use the same interface for rendering. :smiley:

**Comment by ZaneDubya** [comment]
You can select an ascii font with "style: font-family=ascii#" where # is any number between 0 and 9; numbers outside of this range default to 0. Unicode fonts are "style: font-family=uni#" where # is any number between 0 and 2. Default is 1.

Default font remains unicode font number 1.
