### ISSUE TITLE
Ninjitsu books, when equipped, crash the client.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#202]
ItemGumplingPaperdoll.cs:54-58. It seems that Ninjitsu books don't have AnimIDs, which are used to find the texture for Item Gumplings.

**Comment by paezao** [comment]
It's not crashing on 5.0.8.3.

**Comment by ZaneDubya** [comment]
Can you equip the ninjitsu book in the legacy client? What does it look like on the paperdoll?

**Comment by ZaneDubya** [comment]
I cannot equip it in my version of the legacy client (4.x.x.x)

**Comment by ZaneDubya** [comment]
This may be the only item that the developers determined should be equippable after it was originally introduced. Then again, there may be others. I suggest the following 'fix' for this issue:
1. When the player mobile receives a list of worn equipment, check the item data for each item in the list. If the item data's AnimID == 0, then unwear the equipment, placing it in the player's backpack, and give the player an error message ("You can't seem to wear the [item].").
2. When the player attempts to equip an item with no AnimID, play an error noise (UO uses a 'click') and refuse to equip it.
3. When a non-player mobile receives a list of worn equipment, equip each item regardless of the item's AnimID.
4. In ItemGumplingPaperdoll, do not display Items where the AnimID is set to 0.

**Comment by ZaneDubya** [comment]
Wait, hold on a sec. I can't equip it any more, which means this bug no longer exists. The fix was introducing the IsWearable flag in ItemData. I must have changed something in the past 30 days that makes this issue redundant.

Whatever, closing as addressed. I ripped out the stub for the equipment check too. The best code in the client is the code that isn't there. ;)
