### ISSUE TITLE
"Song playback failed. Please verify that the song is not DRM protected."

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#203]
@robertdeclaux said: I gave a break with ZaneDubya's exams, today i tried to compile and run, it says "Error 2015-06-16 21:13:32:3981 Song playback failed. Please verify that the song is not DRM protected. DRM protected songs are not supported for creator games."

This might be caused by [not having windows media player installed](http://stackoverflow.com/questions/5640469/mediaplayer-play-method-throwing-drm-exception). In any case, it worked before, so I'm going to revert the change to the previous way of playing mp3 files.

It's a shame that there isn't a better way to play mp3 files in XNA.

**Comment by PatrikSamuelTauchim** [comment]
Just found this #203 after creating #207 . I have same issue and can confirm that Windows Media Player is not installed. (Windiws 7 **N** edition)

**Comment by ZaneDubya** [comment]
Thanks for confirming, @Eskymak. This bug is my top priority and I will have a fix in ASAP.

**Comment by ZaneDubya** [comment]
Previously working code visible at https://github.com/ZaneDubya/UltimaXNA/blob/6f26ae1b1d1820845fc20450c6b27396ac0560ec/dev/Ultima/IO/MusicData.cs.

**Comment by ZaneDubya** [comment]
Should be fixed in a0ae54cd3ea39a6ec54fa17f7217efd539c32aa3.

**Comment by PatrikSamuelTauchim** [comment]
@ZaneDubya MFPlat.DLL is missing

https://social.msdn.microsoft.com/Forums/en-US/befaf1e7-7bd1-4f17-88cc-ec41be274c74/getting-mfplatdll-is-missing-from-your-computer-error?forum=kinectsdk

**Comment by ZaneDubya** [comment]
How bizarre! I'm using the same code as I was using before, and that didn't have any missing DLLs... I wonder if I should use an audio framework instead of relying on Windows' built in functions (which are obviously not as 'built in' as I thought they were).

**Comment by PatrikSamuelTauchim** [comment]
@ZaneDubya Depends on what edition of Windows you running... It is possible that I also have different editions on my PC at work and home. So somewhere it works fine and somewhere it doesnt.

Those "build in" Windows features are quite tricky, sometimes something does not working because of missing Internet Explorer (had issue with VMWare), sometimes because of missing Media Player (crappy iTunes didnt even throw and error message)...

Using another framework is probably best solution.

**Comment by ZaneDubya** [comment]
Okay. Let's consider what frameworks might be appropriate. I'd like to use a framework coded in c# that can play waves and mp3s. https://github.com/naudio/NAudio fits these requirements. Are there any others?

**Comment by PatrikSamuelTauchim** [comment]
Hah, you need to find someone who understand this stuff. :-)

I just wonder, how this is made in Monogame if does it works.

**Comment by ZaneDubya** [comment]
I believe monogame processes mp3s and exports them as an AudioContent file.
https://github.com/mono/MonoGame/search?utf8=✓&q=mp3

**Comment by ZaneDubya** [comment]
http://www.robburke.net/mle/mp3sharp/ is also a possibility - relatively compact, LGPL licensed.

**Comment by ZaneDubya** [comment]
As of aaae00e317cdb4e1ba9c1dae4cb40613d2291658 the client shouldn't crash when attempting to play an MP3 on a system without WMP installed.

**Comment by ZaneDubya** [comment]
I take it back; mp3sharp is not the kind of code I want to work with.

Honestly, I'm torn. background music is not a huge feature. Perhaps I should just inform the users without WMP that they can't currently play music.

**Comment by fdsprod** [comment]
@ZaneDubya  Have you looked into https://github.com/naudio/NAudio ?

**Comment by ZaneDubya** [comment]
@jeffboulanger I've considered it. It's very well coded, but I don't want to add the entire library, I want to just strip out the mp3 decoding and streaming bits (which is what turned me off of mp3sharp). Not sure how possible that would from a technical standpoint.

Incorporating NAudio may also raise license compatibility issues. :( NAudio is licensed under MS-PL, which applies to it's source if source is distributed, and GPL requires all source be distributed under GPL. Note: I am not a lawyer.

**Comment by ZaneDubya** [comment]
I can't be certain, but it looks like NAudio depends on winmm.dll - which is not included in N Editions.

MP3 frame decoding:
https://github.com/naudio/NAudio/blob/1943205525c1bd4c6dfd4dc20ff9756cbda08c31/NAudio/Dmo/WindowsMediaMp3Decoder.cs

Wave playing (note that we use XNA for this, so it wouldn't be a problem...):
https://github.com/naudio/NAudio/blob/1943205525c1bd4c6dfd4dc20ff9756cbda08c31/NAudio/Wave/MmeInterop/WaveInterop.cs

**Comment by fdsprod** [comment]
@ZaneDubya ya, but you can just install it on the N editions, its just a service pack type of install.  https://www.microsoft.com/en-us/download/details.aspx?id=16546   I have to do this at work.

**Comment by PatrikSamuelTauchim** [comment]
Just a note, with #212  MusicOn is set to False by default and should be True, because we want to have MusicOn by default.  I had music disabled due to this error and forgot to change this back before commit. I will fix that once #210 will get fixed. ;-)

**Comment by ZaneDubya** [comment]
@Eskymak When you have a chance, would you please check out https://github.com/ZaneDubya/MP3Sharp ? I've cleaned up the MP3Sharp code (licensed LGPL) and am considering using it to play MP3s in UXNA. You will need VS2013 to open and run this solution - if you only have 2010, you can start a new solution and drop the two projects (XNA4Sample and MP3Sharp) in there manually). Thanks!

**Comment by PatrikSamuelTauchim** [comment]
@ZaneDubya It plays! I like that song! ;-)

Sent from my Windows 7 Professional **N**

**Comment by ZaneDubya** [comment]
Thanks for checking it out!

**Comment by ZaneDubya** [comment]
Fixed in #214.

**Comment by ZaneDubya** [comment]
Closing as fixed.
