### ISSUE TITLE
Saved settings are lost on client start

### ISSUE THREAD

**Issue by PatrikSamuelTauchim** [ZaneDubya/UltimaXNA#210]
(Some)Settings saved in configuration file are resetted to default values on client start.
- resolution is lost
- gump positions are lost
- maybe something else lost

Last username stays, so this is probably related to some "recent" changes

**Comment by PatrikSamuelTauchim** [comment]
from debug
`Error 2015-07-09 20:32:15:3579 No parameterless constructor defined for type of 'UltimaXNA.Configuration.MouseSettings'.
Error 2015-07-09 20:32:15:3579 Unable to read settings file.  Trying backup file
Error 2015-07-09 20:32:15:3579 No parameterless constructor defined for type of 'UltimaXNA.Configuration.MouseSettings'.
Error 2015-07-09 20:32:15:3735 Unable to read backup settings file. All settings are set to default values.`

**Comment by robertdeclaux** [comment]
I think it still happens, when i closed the client i checked "settings.cfg" that has the entry for the overview gump then i relogin the server, no gumps came up.

**Comment by ZaneDubya** [comment]
Moving this to Milestone 0.6.

**Comment by ZaneDubya** [comment]
Also: settings are not saved on crash.

**Comment by PatrikSamuelTauchim** [comment]
@ZaneDubya  Do we want to save possibly incorrect or corrupted settings on crash?

**Comment by ZaneDubya** [comment]
@Eskymak Yes! But we should also sanity check every setting on load. :)

**Comment by ZaneDubya** [comment]
Ok! Let's figure this one out.

**Comment by ZaneDubya** [comment]
I am opening issue #237 regarding sanity checking properties.

**Comment by ZaneDubya** [comment]
This issue is fixed in b61bf49.
