### ISSUE TITLE
Empty rendered spellbook on sphereserver

### ISSUE THREAD

**Issue by robertdeclaux** [ZaneDubya/UltimaXNA#220]
No console errors.

![spellbook](https://cloud.githubusercontent.com/assets/11157985/8805583/af2419a4-2fda-11e5-8bbc-4603fbdb5b02.PNG)

**Comment by ZaneDubya** [comment]
@robertdeclaux I'd also like to test this one on your server, let me know when I can log in.

**Comment by ZaneDubya** [comment]
Fixed in #280. Thanks @robertdeclaux!
