### ISSUE TITLE
DialougeGump close packet

### ISSUE THREAD

**Issue by robertdeclaux** [ZaneDubya/UltimaXNA#221]
When i send dialogclose packet to client nothing happens, implementing it will be good for refreshing gumps.

http://docs.polserver.com/packets/index.php?Packet=0xBF
![dialogclose](https://cloud.githubusercontent.com/assets/11157985/8805763/ad9517f4-2fdb-11e5-8483-cf49f1c20d6e.PNG)

**Comment by ZaneDubya** [comment]
Implemented in commit 59fcf59b6a7381200b6a0ed03bf3c3ccf2fa4710.
