### ISSUE TITLE
Pop-up tooltip for mobiles.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#235]
Right now, tooltips only work for items. They should work for mobiles as well. This might be easy to implement, or it might be difficult.

**Comment by ZaneDubya** [comment]
Forgive me if I've asked this question before, but do mobiles even have tooltips?

**Comment by PatrikSamuelTauchim** [comment]
@ZaneDubya Yes, if they are tamed for example.

**Comment by ZaneDubya** [comment]
OK! This is in, and only took one line of (admittedly, a little hacky) code. :)
