### ISSUE TITLE
Allow renaming of mobiles using MobileHealthTrackerGump.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#243]
The legacy client allows you to rename another mobile using its equivalent of MobileHealthTrackerGump.

Critical question: how does the server inform the client that it has the right to change a mobile's name?

As a sub-part of this issue, we should hue the MobileHealthTrackerGump gold when a mobile is invincible (what is the flag for invincible?).

**Comment by Vaegrim** [comment]
NameChangeFlag in MobileStatusCompactPacket is the Name Change Permission flag; you've even got it called out in StatusInfoPacket.cs. I think a confirmed change is supposed to send a RenameCharacterPacket

**Comment by ZaneDubya** [comment]
@Vaegrim This is really helpful - thank you.

**Comment by ZaneDubya** [comment]
Starting work on this issue now. Two more issues to go through for Milestone 0.7!

**Comment by ZaneDubya** [comment]
@Vaegrim I've been testing this all evening, and it looks like the name change permission flag is always 0x00 in that packet, regardless of my access level or whether the target animal is tamed. Do you think I'm somehow misreading the data, or that there might be some other flag?

**Comment by ZaneDubya** [comment]
So the text doesn't look perfect, but the interface works perfectly.

**Comment by ZaneDubya** [comment]
Closing as fixed.
