### ISSUE TITLE
World not rendered at all

### ISSUE THREAD

**Issue by PatrikSamuelTauchim** [ZaneDubya/UltimaXNA#255]
Just downloaded current master and world is not rendered at all. I can see just NPCs and wooden wall. Everything else is black.

**Comment by ZaneDubya** [comment]
:( Did you fall through the floor? Try [go Britain

**Comment by PatrikSamuelTauchim** [comment]
Haha, you are right. I was moving on runuo 2.5 and forgot to put some map files to it, so I was always under ground after login. Thanks and sorry for false alarm :-)

**Comment by ZaneDubya** [comment]
No prob - thanks for checking it out!
