### ISSUE TITLE
Completely new html layout engine.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#257]
The current layout engine is awful. We can do better.

**Comment by ZaneDubya** [comment]
This issue has ballooned into a brand new html layout engine.

**Comment by ZaneDubya** [comment]
I have completed and am merging the new html layout engine. It may well cause graphical errors and crashes. Let me know if you find any. I will close this issue with M0.7; I assume that if there are any problems, they will have been discovered by then.

**Comment by ZaneDubya** [comment]
Skills scroll and vendor buy/sell menus are a little buggy...

**Comment by ZaneDubya** [comment]
Vendor buy/sell menus fixed. They look great, by the way.

**Comment by robertdeclaux** [comment]
Buy/sell menus are awesome! Can we just add some thing to them? Holding + or - icon down can increase or decrease the amount of the item (faster), its an usual thing for players they will want it later on...

**Comment by ZaneDubya** [comment]
@robertdeclaux Yes, we can do that. Pause for 1/2 second on mouse down and then add items at a rate of 5-10/second.

**Comment by robertdeclaux** [comment]
That will be perfect!

**Comment by ZaneDubya** [comment]
Looks like html link regions for images are bugged...

**Comment by robertdeclaux** [comment]
Not sure related to this issue but on sphere text inputs does not sent to the server.
![ekran goruntusu 22](https://cloud.githubusercontent.com/assets/11157985/9350436/ba95e0de-4659-11e5-9206-0d4608ae384f.png)
Error message says there must be at least 3 chars on your input (blackrock). Another issue, font colors are different on UltimaXNA and default client.

Default client's colors
![ekran goruntusu 23](https://cloud.githubusercontent.com/assets/11157985/9350599/e7ff6030-465a-11e5-90e3-2ecc48751201.png)

**Comment by ZaneDubya** [comment]
@robertdeclaux Thank you - I will see if I can't fix both of those issues.

**Comment by ZaneDubya** [comment]
Broke out better mouse event handling to #311.

**Comment by ZaneDubya** [comment]
@robertdeclaux Fixed the text colors. Not sure what is causing the client not to send text to sphere server... It is working on RunUO.

**Comment by ZaneDubya** [comment]
Opening #312 for this issue.
