### ISSUE TITLE
Implement MsgType 0x03 for speech.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#258]
Sphere server sends speech with MsgType 0x03 - which neither RunUO nor PolServer use. It appears to be a standard overhead speech type. Not sure if it shouldn't be treated differently.

**Comment by ZaneDubya** [comment]
Current status of MsgType 0x03 speech: ;)
![ekran goruntusu 4](https://cloud.githubusercontent.com/assets/11157985/9085627/171e85f0-3b87-11e5-9f3c-3820e4851c3b.png)

**Comment by ZaneDubya** [comment]
Implemented in 3f06ef53b0051431e01e384feed2ac9c9e20e333.

**Comment by robertdeclaux** [comment]
Working great!

**Comment by robertdeclaux** [comment]
![ekran goruntusu 13](https://cloud.githubusercontent.com/assets/11157985/9289228/2ec6388c-4371-11e5-862f-bd3af4d53276.png)
Just a very small problem, duplicate message appears on console too.

**Comment by robertdeclaux** [comment]
:+1:

**Comment by ZaneDubya** [comment]
@robertdeclaux Do you mean the message occurs once, or twice in the console? Paste a screenshot? Thanks!

**Comment by robertdeclaux** [comment]
Sorry i mean chat log by "console", i just realized that chatting shows duplicated text too. It's not related to MsgType 0x03 i think.
![ekran goruntusu 13](https://cloud.githubusercontent.com/assets/11157985/9289490/8a52b49c-437a-11e5-8040-3fbaef30bc74.png)
![ekran goruntusu 16](https://cloud.githubusercontent.com/assets/11157985/9289499/b08c765c-437a-11e5-92cf-3276ba589d23.png)

**Comment by ZaneDubya** [comment]
Haha, it shouldn't be down there? Ok! I'll remove it. :)

**Comment by robertdeclaux** [comment]
Unless speaker is yelling it shouldn't be down there. :)

**Comment by ZaneDubya** [comment]
That is JUST the information I needed. Thanks!
