### ISSUE TITLE
Stacks of scrolls look incorrect.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#259]
The stacking for scrolls places the second scroll way, way to the left and bottom of the first. Obviously this is an error.

**Comment by paezao** [comment]
This happens to bandages as well.

**Comment by paezao** [comment]
Looks like the offset as 5 works with most stuff. It doesnt work for coins though but that works getting the offset from ItemData.Unkown4.

**Comment by ZaneDubya** [comment]
Interestingly, stacked items look fine on the ground. They only look weird in the inventory. I think this is a UI bug, not a bug reading data.

**Comment by ZaneDubya** [comment]
Simple fix.

**Comment by robertdeclaux** [comment]
:+1:
