### ISSUE TITLE
Possible memory leak when viewing large crowds of mobiles.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#260]
On @robertdeclaux's server, when he uses the command .allshow causing all his mobiles to appear, the framerate steadily decreases until each frame is taking over a second to display. Something wonky is going on - not sure what.

**Comment by ZaneDubya** [comment]
@robertdeclaux Is there a way to turn .allshow off? When you do so, does the framerate return to normal?

**Comment by PatrikSamuelTauchim** [comment]
@robertdeclaux @ZaneDubya Can you tell us how many mobiles we have to actually spawn to notice this issue? We can try to reproduce this with RunUO.

**Comment by ZaneDubya** [comment]
@Eskymak That would be awesome! A random NPC spawner?!

It was a ton of mobiles. Looked like at least enough to fill the screen at 1024x768. Sorry I don't have a picture. :(

**Comment by PatrikSamuelTauchim** [comment]
@ZaneDubya Just tested with few hundreds of NPC at FullHD. RunUO was running on the same VM and probably making performance bad but...
![ultimaxna](https://cloud.githubusercontent.com/assets/11310587/9259495/2ba0cc0c-420a-11e5-8e49-9cdeba2eeded.jpg)
When I was transferring screenshot and client was on  background, I faced another #262 and cannot login at this area anymore, even it was running for a while.

**Comment by robertdeclaux** [comment]
![1](https://cloud.githubusercontent.com/assets/11157985/9260972/b20e9e50-4213-11e5-8ec2-fc756b0070bc.png)
1500+ playes on screen, when i try to close allshow client crashes.

debug file has so many remove entity packets entire log from this sesion 28mb but the last lines are

Info 2015-08-13 23:36:28:1996 Server - > Client
Info 2015-08-13 23:36:28:1996 Id: 0x1D Name: Remove Entity Length: 5
Info 2015-08-13 23:36:28:1996 
        0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
       -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
0000   1D 00 1F A1 73                                    ....s

Error 2015-08-13 23:36:28:2006 Nesne başvurusu bir nesnenin örneğine ayarlanmadı.
Error 2015-08-13 23:36:28:2006 Object reference not set to an instance of an object.

**Comment by robertdeclaux** [comment]
Log when i try to close .allshow
![ultima xna](https://cloud.githubusercontent.com/assets/11157985/9289338/b256314a-4374-11e5-94e6-0039e506d581.png)

**Comment by ZaneDubya** [comment]
WorldInput lines 217-219:

```
                // Tell the player to stop moving.
                Mobile m = (Mobile)WorldModel.Entities.GetPlayerEntity();
                m.PlayerMobile_Move(Direction.Nothing);
```

Your player object was disposed. That's bizarre.

**Comment by ZaneDubya** [comment]
@robertdeclaux When you have a moment, I'd like to test this on your server. Let me know when/how I can log in. Thanks!

**Comment by ZaneDubya** [comment]
I believe this issue is fixed now. Thanks @robertdeclaux for letting me bugtest on your server.
