### ISSUE TITLE
Cursor runs of out client window while closer to the bottom border

### ISSUE THREAD

**Issue by PatrikSamuelTauchim** [ZaneDubya/UltimaXNA#264]
When I move cursor close to the bottom of the client window, Windows cursor appears outside of client window. Bottom area of client is unreachable, cursor is running out of window.

Resolution was FullHD
![ultimaxna_cursor](https://cloud.githubusercontent.com/assets/11310587/9260078/20ad26c0-420e-11e5-9761-700087083941.jpg)

**Comment by ZaneDubya** [comment]
@Eskymak Try mousing out at the sides and compare the positions of the ultima cursor and window cursor. Is the y position of the cursor incorrect throughout the height of the window, but more incorrect as you approach the bottom? What is your DPI? Is Windows' scaling enabled?

**Comment by PatrikSamuelTauchim** [comment]
@ZaneDubya I think, that it has something to do with Windows taskbar.
Problem is there only when client window is maximalized.
When it is not maximalized, but is stretched to cover full screen, and even under taskbar, it works just fine.

**Comment by PatrikSamuelTauchim** [comment]
@ZaneDubya When I set Windows taskbar to right side of screen, I have same issue on right side and no issue at bottom. :-)

**Comment by ZaneDubya** [comment]
Very interesting! I notice now that the trees in your screen shot do seem to be a little squashed. :)

**Comment by PatrikSamuelTauchim** [comment]
@ZaneDubya  I also noticed issue with fonts on high resolution - they are not smooth while moving gump. It is probably also related to this. If not resolved after closing this, I will create new issue.

**Comment by ZaneDubya** [comment]
@Eskymak Can you clarify? I think that your game play window was squashed, which will result in blurred textures. Is this what you're talking about?

**Comment by ZaneDubya** [comment]
A fix for this would be to limit the display viewport to the size of the current game window...

**Comment by PatrikSamuelTauchim** [comment]
Yep, it is squashed when maximalized.
![ultimaxna_cursor2](https://cloud.githubusercontent.com/assets/11310587/9288276/fe48e918-4346-11e5-9537-d136180dee89.jpg)

**Comment by ZaneDubya** [comment]
Ok @Eskymak, I think I have this fixed.

**Comment by ZaneDubya** [comment]
I fixed it by limiting your ability to select play window resolutions greater than your current desktop size. So if your play window couldn't fit on your desktop, then you shouldn't see the option to select that size.

I'm closing the issue, let me know if this is not fixed.
