### ISSUE TITLE
Casting a spell on an NPC with position.Z < 0 is bugged.

### ISSUE THREAD

**Issue by robertdeclaux** [ZaneDubya/UltimaXNA#271]
![1](https://cloud.githubusercontent.com/assets/11157985/9293812/d2ae78bc-4441-11e5-86e6-4c37886d0410.png)
![2](https://cloud.githubusercontent.com/assets/11157985/9293813/d2b39b76-4441-11e5-8485-f29b92e2bf3b.png)
When i cast spell on NPCs they disapper for 1-2 seconds then they come back from up and energy bolt animation moves very slow.

**Comment by ZaneDubya** [comment]
I cannot replicate this issue. Can you provide more detailed testing instructions?

That NPC is right on the edge of the client-server update range, which should be about 19 tiles. Certainly, it would be way off screen on the legacy client. It could have walked out of range, which would have bugged the effect graphic. I will take a look and see if I can fix that.

Try firing spells at closer npcs. Same issue?

**Comment by robertdeclaux** [comment]
Zane found out that caused by -z positions.

**Comment by ZaneDubya** [comment]
@robertdeclaux Where in the world is this occurring? Can you give me a xyz position?

**Comment by robertdeclaux** [comment]
Destard dungeon (1176,2636,0,0)

**Comment by ZaneDubya** [comment]
Error is in Effect ctors. I am setting the position of the mobile targeted. I wonder why I did that - it seems such a bad idea in retrospect...

**Comment by ZaneDubya** [comment]
Fixed.
