### ISSUE TITLE
Label messages (speech type 0x03) do not display on items in containers.

### ISSUE THREAD

**Issue by robertdeclaux** [ZaneDubya/UltimaXNA#272]
![ekran goruntusu 21](https://cloud.githubusercontent.com/assets/11157985/9293901/6514158e-4444-11e5-95ae-2695946057d9.png)
Single clicking on player vendor items does not show its name (or properties) but it appers on journal.

**Comment by ZaneDubya** [comment]
Single click does not show names on any item in any backpack.

**Comment by ZaneDubya** [comment]
On Sphere, you have the option to send a Label (msg type 0x03) on clicking an item in a container. This should result in the name of the item being displayed above the item in the container.

**Comment by ZaneDubya** [comment]
Getting close to finished on this issue...

@robertdeclaux Do you know how the server enables/disables pop-ups? Some flag in the Enable Features packet?

**Comment by robertdeclaux** [comment]
I'm not sure but it can be related to aos features which (all) disabled on my server. I'm looking for more information.

**Comment by ZaneDubya** [comment]
I've merged my proposed change to master and am closing this issue as fixed. Please let me know if it does not work on your end.

Note that this change breaks the appearance of some text in the bottom left chat interface / journal. I will go through and rigorously test each of the message types in Milestone 0.7.
