### ISSUE TITLE
Move to MonoGame

### ISSUE THREAD

**Issue by Vodacek** [ZaneDubya/UltimaXNA#28]
Why not to port this from XNA to MonoGame? https://github.com/mono/MonoGame
If you don't know MonoGame is Open source XNA implementation that add support to many other platforms like Linux, android, iOS etc. It would be great to have it here!

Thank you Eskymak for letting me know about his project!

**Comment by ZaneDubya** [comment]
This is an _interesting_ idea. My time is limited, and I am spending it on features and bug fixes. When the client is feature complete, I may well look into this!

If you think you can take this on yourself, please do so! I would be happy to switch to Monogame if it takes little effort on my part and things run just as well (or better!).

**Comment by Vodacek** [comment]
I can try it, but I am affraid that we get many exceptions in Texture2D.SetValue calls, this area is not in good condition in MonoGame as far as I know :-)

**Comment by ZaneDubya** [comment]
I'm going to close this issue for now. When the client is feature complete, we can definitely contemplate moving it to Monogame.
