### ISSUE TITLE
Movement is bugged when "teleport" movement received while moving.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#285]
To reproduce:
1. Tame an animal.
2. "All follow"
3. Start running around (might require a teleport).
4. Gaze at the crazy movement of you pet!

**Comment by denizsokmen** [comment]
Have you tried it on runuo and is it like the pet suddenly teleports on you? If that's the case, that's how it works in RunUO to make sure your pet doesn't get out of your sight.

**Comment by ZaneDubya** [comment]
@denizsokmen Yes - although slightly more buggy than that! I think my movement routine gets confused when it receives a teleport move in the middle of another move.

**Comment by ZaneDubya** [comment]
Just had a eureka moment. Let's see if I can fix this...

**Comment by ZaneDubya** [comment]
Should be fixed as of 792f21917943452a9e1f6f889d388cdbdddf3ce4. I'm sure someone will open a new issue if this is not the case. But it looks good to me.
