### ISSUE TITLE
Double clicking spell in spellbook index should cast the spell.

### ISSUE THREAD

**Issue by robertdeclaux** [ZaneDubya/UltimaXNA#294]
Double clicking on a spell opens the details page instead of casting the spell.

**Comment by ZaneDubya** [comment]
"double clicking on a spell" - where are you double clicking? Is this in the index?

**Comment by robertdeclaux** [comment]
![ekran goruntusu 6](https://cloud.githubusercontent.com/assets/11157985/9370275/bbd8a5c0-46d7-11e5-89e4-76ed641de18a.png)
When we double click on earthquake (on default client) it casts the spell.

**Comment by ZaneDubya** [comment]
Ok, I'll take a look at that. Thanks!

**Comment by robertdeclaux** [comment]
It's not releated to this issue but on sphere (with old spellbook packets) opening spellbook takes nearly 1 second.

**Comment by ZaneDubya** [comment]
Does it take that long on legacy client?

**Comment by robertdeclaux** [comment]
No it is instant on legacy client, if we are preparing all the info pages when the spellbook gump shown may be that is causing it. Legacy client spell info pages have that 1 second lag.

This is the screen i mean by spell info pages
![ekran goruntusu 7](https://cloud.githubusercontent.com/assets/11157985/9370539/cef3b094-46d9-11e5-9cbb-1224054c2fcf.png)

**Comment by ZaneDubya** [comment]
Ok @robertdeclaux, I'll rewrite the spellbook gump so that it only prepares the pages you are currently looking at.

**Comment by ZaneDubya** [comment]
I should do a better job of keeping issues focused. I'm going to close this one and open a new one.
