### ISSUE TITLE
Spell icons cast different spells

### ISSUE THREAD

**Issue by robertdeclaux** [ZaneDubya/UltimaXNA#295]
![ekran goruntusu 4](https://cloud.githubusercontent.com/assets/11157985/9370039/fe6bdd00-46d5-11e5-88ee-c692e5058220.png)
For example if you click on energy bolt icon it casts dispel (which is previous spell).

**Comment by ZaneDubya** [comment]
The 'previous' comment makes this a perfect bug report! I know why this is happening and can fix it soon. Thank you!

**Comment by naggie** [comment]
zero/one offset confusion? :D

**Comment by ZaneDubya** [comment]
@naggie Nailed it ;)

**Comment by ZaneDubya** [comment]
Fixed, thanks @robertdeclaux
