### ISSUE TITLE
map button size and functionality

### ISSUE THREAD

**Issue by Rex-deadwall** [ZaneDubya/UltimaXNA#299]
pressing the Map button on the Menu Bar opens and closes the small gump map instead of opening the small map, then opening the big map, then opening the small map, etc.
view the web in chrome firefox.
https://dl.dropboxusercontent.com/u/5608436/Error-map.webm

**Comment by Rex-deadwall** [comment]
also alt-R is the hardcoded hotkey for opening the map.

**Comment by ZaneDubya** [comment]
@Rex-deadwall Thank you for posting this issue. I'll have it fixed shortly.

**Comment by robertdeclaux** [comment]
I think it's not hardcoded but default, you can change or delete it later.

**Comment by ZaneDubya** [comment]
We can definitely change it from hard coded to changeable when we get macros in! Don't ask me when that will happen ;)

**Comment by ZaneDubya** [comment]
Added in 3e740cf. Closed as addressed.
