### ISSUE TITLE
MissingFuction-HealthBarMenu

### ISSUE THREAD

**Issue by Rex-deadwall** [ZaneDubya/UltimaXNA#300]
you can drag off your from character and get the health bar, but double clicking it does not bring up the large stats gump.
https://dl.dropboxusercontent.com/u/5608436/MissingFuction-HealthBarMenu.webm
open webm in chrome or firefox

**Comment by ZaneDubya** [comment]
@Rex-deadwall Thank you for posting this issue - this shouldn't be that difficult to add!

**Comment by ZaneDubya** [comment]
Added in f1f0369. I've made it so that double clicking the gump toggles it, not necessary opens.
