### ISSUE TITLE
Error-Text Color

### ISSUE THREAD

**Issue by Rex-deadwall** [ZaneDubya/UltimaXNA#301]
The text color can be changed in the options menu from blue to something else, but it doesn't actually change it IG for the player.
The custom text color does not show up colored in the journal.
https://dl.dropboxusercontent.com/u/5608436/Error-TextColor.webm

**Comment by PatrikSamuelTauchim** [comment]
Yep, it is no implemented yet. I was already looking for place in code where I color of speech and other texts is defined, but without success.

**Comment by ZaneDubya** [comment]
The color of the text you select in the options gump (thanks @Eskymak!) is now used for your ingame speech.

**Comment by ZaneDubya** [comment]
Breaking out two issues, closing this one:
Emote mode #313
Journal colors #314.
