### ISSUE TITLE
Next speech CTRL+Q

### ISSUE THREAD

**Issue by Vodacek** [ZaneDubya/UltimaXNA#31]
In original client CTRL+Q gets last user written text.

**Comment by ZaneDubya** [comment]
Could you add additional documentation of what "last user written text" is, or link to a page that describes the desired behavior? Thank you!

**Comment by PatrikSamuelTauchim** [comment]
Ctrl-Q = Circle backwards through the things you have said today
Ctrl-W = Circle forwards through the things you have said today
http://www.uoguide.com/Classic_Client

You can circle through the already said text / used commands and say/use them again. Really usefull for emoting, greetings, GM commands.

**Comment by robertdeclaux** [comment]
As an example, when you say "hello robert" in game after pressing enter, if you push ctrl-q it will take "hello robert" to chat buffer(and shows as it's typed) but you must press enter to send it.

**Comment by ZaneDubya** [comment]
Implemented in #73 by @robertdeclaux
