### ISSUE TITLE
Text box: implement emote, yell, party, guild, and alliance.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#313]
Typing colon followed by space as the first two characters in the chat text entry box should cause the text entry box to enter 'emote mode'. Sending text while in emote mode should send an emote message, not a chat message. Emote mode should be cleared after sending text. Typing backspace when the text buffer is empty while in emote mode should clear emote mode. Emote mode colors should be implemented.

**Comment by PatrikSamuelTauchim** [comment]
**":"** (semicolon) is used for whisper in same way as ":" for emote
**!** is used for yell
**/** for party
**\** for guild
**|** Alliance
http://www.uoguide.com/Chat

**Comment by ZaneDubya** [comment]
Nice. Thank you @Eskymak

**Comment by ZaneDubya** [comment]
Implemented! Moved party chat to #330, as it relied on a new set of packets which have not yet been implemented.

**Comment by ZaneDubya** [comment]
Merged in #451. Please open a new issue for any bugs/feature additions with the chat window.
