### ISSUE TITLE
Journal text colors do not reflect spoken text colors.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#314]
Ideally, the color of text within the journal will match the color of text within the game. This is not yet implemented.

**Comment by PatrikSamuelTauchim** [comment]
Also the text in chat input field should match the color of the active mode - speech/emote/party/guild/...

**Comment by ZaneDubya** [comment]
Looks good, the only remaining thing to do is to work on the spacing of text lines; they're a little too spread out at the moment. Should be a quick fix.

**Comment by ZaneDubya** [comment]
Ok, looking good! Some small business left to do with the spacing, but I think it's good enough to move forward.
