### ISSUE TITLE
item hue change

### ISSUE THREAD

**Issue by Vodacek** [ZaneDubya/UltimaXNA#32]
When server sends new item packet (0x1A) with changed hue game doesn't update this information.

**Comment by ZaneDubya** [comment]
@Vodacek If I were running a vanilla RunUO server with standard client data files, is there any place on the map where I could see this happen? In that place, what is the result in the classic client and in UltimaXNA?

**Comment by Vodacek** [comment]
just add any item [add item 128 and then change its hue [set hue 20, color of this wall should be pink
 

---

**Comment by ZaneDubya** [comment]
Interestingly, I can get mobiles to change hues, but not any items at all, whether in a player's inventory or in the world. I think I understand how to get both working - but they'll require separate fixes.

**Comment by ZaneDubya** [comment]
eaf8a0146b7d38716c22d3b2c547211e1398395b Items in the world now update their hue every frame.

**Comment by ZaneDubya** [comment]
7d892e68265db07f65391b01f4e5f474073ed030 Items in inventory / on paper doll can now be targeted as well!

**Comment by ZaneDubya** [comment]
@Vodacek Is there anything else that should be targetable but can't be targeted?

**Comment by Vodacek** [comment]
@ZaneDubya thank you, now hues are updated correctly :-)
