### ISSUE TITLE
.Hidden and sounds still play

### ISSUE THREAD

**Issue by Rex-deadwall** [ZaneDubya/UltimaXNA#320]
While in owner mode i set myself hidden and walked around, and i could still hear footsteps, no sounds should play when in hidden mode.

**Comment by ZaneDubya** [comment]
@Rex-deadwall Thank you for reporting this issue. I've added a fix in 5f425b2, which should be merged as part of a bunch of footstep enhancements in the next few days.

**Comment by ZaneDubya** [comment]
Or tonight. ;) Closing as addressed.
