### ISSUE TITLE
Game takes endless times to load

### ISSUE THREAD

**Issue by 3HMonkey** [ZaneDubya/UltimaXNA#328]
After joining the game, the world loads and you're able to run around on map but the world is not seen to be spawned, no doors, no npcs , no items etc. If you stay for a bit (about 10-15 minutes) you can see npcs spawning naked. After another 10 minutes they have clothes on. Also the character is swapping to his old point he stood before 5 minutes. Same with texts you post. You can wait some minutes to be able to read it.
And it seems that something is blocking the connection. This is tested on local server and live server (online) with 7.0.15.1 and mondains legary you prefered.

Well I am a programmer and have to take a look into this system and I really like your idea building up this old game with xma and so on.

Maybe its because of this:
The console is telling me (spamming about 10 times per second while moving for example):
"Unhandled packet with id: 0xf3, pissoble dubid: 0x00"

Update: Seems like 0xF3 is a "[0xF3] Object Information (SA)" Packet by the server

**Comment by ZaneDubya** [comment]
@Gr3enP0ison - thank you for reporting this issue. What server software and version of the same are you using? Does this happen on a vanilla installation of that server?

**Comment by 3HMonkey** [comment]
Runuo 2.3 and 2.5 clean and 2.5 + Vita nex core

**Comment by 3HMonkey** [comment]
Maybe we can skype these days cause i really want to help programming the client.

**Comment by ZaneDubya** [comment]
@Gr3enP0ison I would welcome any help you could offer!

Your issue is odd - I test on 2.3 clean, and I am not experiencing anything like this. Are you experiencing similar problems with the classic client? If you try running the ML classic client, are you seeing the same issue?

**Comment by ZaneDubya** [comment]
Here's another thought - as far as I know, [RunUO preferentially sends the 0x1A packet to clients with a version lower than 7.0.0.0](https://github.com/brodock/runuo/blob/b2b7cef1dcf597266d41be9ab731b35368916f9c/Server/Item.cs#L2702). I have set up the xna client to send, by default, version 6.0.6.2. Is it possible that your copy of the xna client is sending the wrong version? Would you set a breakpoint at line 261 of LoginClient.cs and see what version is being sent by your copy of the client?

**Comment by 3HMonkey** [comment]
7.0.15.1 , because i set it to this version inside the "UltimaOnlineSettings.cs" line 26 : ClientVersion = new byte[] {7, 0, 15, 1}; This was just a test if it will work afterwards, but the same problem.

2nd : Yes on both clients. ML classic I downloaded here and UO:classic client 7.0.15.1

**Comment by 3HMonkey** [comment]
Another idea: what branch are u using?

**Comment by ZaneDubya** [comment]
> 7.0.15.1 , because i set it to this version inside the "UltimaOnlineSettings.cs" line 26 : ClientVersion = new byte[] {7, 0, 15, 1};

I believe this is causing the problem. If you set version to any value less than 7.0.0.0, RunUO will stop sending you the missing packet. You can set the default value in UltimaOnlineSettings.cs, as you already know; you may also need to delete settings.cfg in your bin directory.

I am tempted to simply implement packet 0xF3, but I don't want to start implementing SA/HS features before we have ML working.

> Another idea: what branch are u using?

I am using the master branch.

**Comment by 3HMonkey** [comment]
Mhh strange, it makes no difference setting the client version less 7.0.0.0 or above 7.0.0.0. But if I set it to something less than 7 the client is crashing.

**Comment by ZaneDubya** [comment]
What error message are you getting? Can you post the stack trace?

**Comment by 3HMonkey** [comment]
It just comes up sometimes. Nothing important, I just noticed it.
Inside:
private IAnimationFrame getFrame(int bodyID, int hue, int facing, int action, float frame, out int frameCount)
        {
            if (bodyID >= 500 && bodyID <= 505)
                patchLightSourceAction(ref action, ref frame);

```
        frameCount = 0;

        // get the resource provider
        IResourceProvider provider = ServiceRegistry.GetService<IResourceProvider>();
        IAnimationFrame[] frames = provider.GetAnimation(bodyID, action, facing, hue);
        if (frames == null)
            return null;
        frameCount = frames.Length;
        int iFrame = (int)frame; // frameFromSequence(frame, iFrames.Length);
        if (frames[iFrame].Texture == null)
            return null;
        return frames[iFrame];
    }
```

Sorry I have no trace atm because it just come up sometimes. 

Mhh I thought about the other bug. Maybe its because of the server version. I gonna check this.

**Comment by 3HMonkey** [comment]
Ok I got it. It was the settings.cfg!! I deleted this file every client restart but the content of the "new" generated file was old. I really should restart my PC more often :). So it seems like there was some kind of cache which saved the old settings.cfg. After a restart it was working fine with 6.9.9.9 inside settings. Now I can jump up inside your code to help a bit :) Anyway, thank you for your time helping me !!!

Last question: Is there a possibility to higher the loading range for example if you higher the resolution of your game window?

**Comment by PatrikSamuelTauchim** [comment]
@Gr3enP0ison I had same issue once, solved with removing whole UltimaXNA directory.

I think, that client is also making backup of settings.cfg file, so even if you remove it, it can be restored to original, corrupted state from that backup.

Would be nice to see that corrupted file to know, what is actually wrong with it. Do you have it in recycle bin maybe?

About increasing of loading range for hight resolutions, one limit is in server (RunUO) itself. I was already playing with that, but I was unable to get any result. Not sure, if I missed something in RunUO or there is also limit in UltimaXNA.

**Comment by 3HMonkey** [comment]
@Eskymak I found out that you can higher the vieport distances inside RUNUO by changing the value inside "Core.GlobalMaxUpdateRange".
There are also some scripts inside RUNUO where you'll have to change specific static variables. For example: Map.Get*InRange() and Utility.InUpdateRange()

**Comment by PatrikSamuelTauchim** [comment]
@Gr3enP0ison I think that I already increased GlobalMaxUpdateRange without any effect. Is that working for you?

**Comment by PatrikSamuelTauchim** [comment]
@Gr3enP0ison On server, where you counting with UltimaXNA high resolution support, it can be also good to ask client for resolution used and then set MaxUpdateRange for each player based on that resolution.

It can be actually really tricky to use this on real shard, since players with high resolution will have big advantage over players with low resolutions.

I can also imagine UltimaXNA specific packets for handling this kind of negotiation. Ofcourse, you can just ask player via gump. :-)

If you have lower resolution, It would be also possible to mark objects (mobiles) outside visible range on radar. Endless possibilities with UltimaXNA!

**Comment by 3HMonkey** [comment]
You're right. I am also planning getting into the code of UltimaXNA but it is really poorly documented so that makes it very hard to understand the code. At the moment I try to find out where the camera is located because i want to add a zoom function and so on. Also I am planning a better rendering for textures and and and.

**Comment by PatrikSamuelTauchim** [comment]
I am sure @ZaneDubya can explain more about rendering. For me is also mostly black box. :-)

In combination with higher resolutions on smaller screens, zoom would be really cool feature

All you looking for is probably in this file:
https://github.com/ZaneDubya/UltimaXNA/blob/master/dev/Ultima/World/WorldViews/IsometricView.cs

**Comment by ZaneDubya** [comment]
@Gr3enP0ison Glad to hear things are working. Sorry for the trouble. Both you and @Eskymak are correct in your assumptions about a settings cache - you have to delete both settings.cfg and settings.cfg.bak to reset all settings. Because you found out what setting was causing this issue, I'm going to close this issue.
