### ISSUE TITLE
Implement party system, including chat.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#330]

**Comment by msx752** [comment]
PartySystem is ready and all functions are working. EXCEPT three important problem.
1. i need when player clicked the private message button or Green button after that chat will change /p1 [username] 
2. when partymember was going far away, i couldn't get the member's Status, so i can't update MemberStatus.
3. need Partymember Status be targetable for spells.

![partys1](https://cloud.githubusercontent.com/assets/11164838/12379515/4675b3a4-bd65-11e5-9013-34af8c161129.png)
![partys2](https://cloud.githubusercontent.com/assets/11164838/12379514/4674cd54-bd65-11e5-908a-d40eae3700d0.png)

**Comment by ZaneDubya** [comment]
Merged in #451. Please open a new issue for any bugs/feature additions with the party system.
