### ISSUE TITLE
Overhead font and colors (sphereserver)

### ISSUE THREAD

**Issue by robertdeclaux** [ZaneDubya/UltimaXNA#334]
They are a little bit different than the legacy client (on sphereserver emulator LBR settings)

 Legacy
![ekran goruntusu 28](https://cloud.githubusercontent.com/assets/11157985/9737710/a79cea0c-5650-11e5-919f-8c2833a00d67.png)
![ekran goruntusu 29](https://cloud.githubusercontent.com/assets/11157985/9737711/a7a15b78-5650-11e5-9862-5441570f572e.png)
![ekran goruntusu 30](https://cloud.githubusercontent.com/assets/11157985/9737712/a7a51aa6-5650-11e5-8d2d-fac2e470932a.png)
![ekran goruntusu 34](https://cloud.githubusercontent.com/assets/11157985/9737713/a7bda71a-5650-11e5-8f1c-b5a890ca99b2.png)

UltimaXNA
![ekran goruntusu 31](https://cloud.githubusercontent.com/assets/11157985/9737723/b6e9e5aa-5650-11e5-8335-135793c268d9.png)
![ekran goruntusu 32](https://cloud.githubusercontent.com/assets/11157985/9737724/b771b4bc-5650-11e5-8a23-cb2db9447d31.png)
![ekran goruntusu 33](https://cloud.githubusercontent.com/assets/11157985/9737725/b7f3d83e-5650-11e5-99d1-f6a207a3559e.png)

**Comment by ZaneDubya** [comment]
@robertdeclaux I'm looking into the blue font issue. The double-pixel outline should be fixed now.

**Comment by ZaneDubya** [comment]
@robertdeclaux Should be fixed.

**Comment by robertdeclaux** [comment]
Item overheads are perfect now, but mobiles may require a little bit tunning later on outline color.
![ekran goruntusu 35](https://cloud.githubusercontent.com/assets/11157985/9739546/ec8b73d8-5658-11e5-83be-3420d4965489.png)
thank you!
Note: it may seem a render issue i just paste legacy client's view on it

**Comment by ZaneDubya** [comment]
Can you give me an example of the "outline color" that is incorrect? Is this on the text?

**Comment by ZaneDubya** [comment]
@robertdeclaux The outline should always be black?

**Comment by robertdeclaux** [comment]
I'm not sure about this give me a little bit time to check

**Comment by robertdeclaux** [comment]
It seems like unicode fonts have always black outline, I took screenshots of all fonts from legacy client
![1](https://cloud.githubusercontent.com/assets/11157985/9740047/717f3aa0-565b-11e5-86ad-91dfb213a385.png)
![ekran goruntusu 36](https://cloud.githubusercontent.com/assets/11157985/9740048/717f80aa-565b-11e5-995a-cda3394d9dd5.png)
![ekran goruntusu 38](https://cloud.githubusercontent.com/assets/11157985/9740049/718625e0-565b-11e5-96e5-99a94198ea80.png)
![ekran goruntusu 52](https://cloud.githubusercontent.com/assets/11157985/9740255/6fd9f87e-565c-11e5-99f3-c3629573776d.png)
![ekran goruntusu 41](https://cloud.githubusercontent.com/assets/11157985/9740050/7188593c-565b-11e5-9b33-d4abbcaa8160.png)
![ekran goruntusu 42](https://cloud.githubusercontent.com/assets/11157985/9740051/718d2886-565b-11e5-9221-3a29eb6e0ab7.png)
![ekran goruntusu 43](https://cloud.githubusercontent.com/assets/11157985/9740052/719155a0-565b-11e5-942d-474614d0c110.png)
![ekran goruntusu 44](https://cloud.githubusercontent.com/assets/11157985/9740053/719c3a7e-565b-11e5-9197-2ecbeac5ff6e.png)
![ekran goruntusu 45](https://cloud.githubusercontent.com/assets/11157985/9740054/719d6d72-565b-11e5-9c3c-256bce4a9de5.png)
![ekran goruntusu 46](https://cloud.githubusercontent.com/assets/11157985/9740055/71a50258-565b-11e5-8015-b15b3ed16f2e.png)
![ekran goruntusu 47](https://cloud.githubusercontent.com/assets/11157985/9740056/71a65a4a-565b-11e5-9b18-dfc2f1ffc42b.png)

**Comment by ZaneDubya** [comment]
Ok, complete.
