### ISSUE TITLE
Crash report in item rendering

### ISSUE THREAD

**Issue by gtozzi** [ZaneDubya/UltimaXNA#344]
Hey,

I think this is due to some "unknown tile".

It excepts {System.NullReferenceException} on ItemView.cs, line 52: "
DrawArea.Y = DrawTexture.Height - IsometricRenderer.TILE_SIZE_INTEGER + (Entity.Z \* 4);
"

DrawTexture is null.

Last log says:
"Requested texmap texture #13287 does not exist. Replacing with 'unused' graphic."

Thank you for sharing this nice project, let me know if you need more info :)

Full Exception:
-       $exception  {System.NullReferenceException: Riferimento a un oggetto non impostato su un'istanza di oggetto.
  in UltimaXNA.Ultima.World.EntityViews.ItemView.Draw(SpriteBatch3D spriteBatch, Vector3 drawPosition, MouseOverList mouseOverList, Map map, Boolean roofHideFlag) in c:\UltimaXNA\dev\Ultima\World\EntityViews\ItemView.cs:riga 51
  in UltimaXNA.Ultima.World.WorldViews.IsometricRenderer.DrawEntities(Map map, Position3D center, MousePicking mousePicking, Vector2& renderOffset) in c:\UltimaXNA\dev\Ultima\World\WorldViews\IsometricView.cs:riga 215
  in UltimaXNA.Ultima.World.WorldViews.IsometricRenderer.Update(Map map, Position3D center, MousePicking mousePick) in c:\UltimaXNA\dev\Ultima\World\WorldViews\IsometricView.cs:riga 93
  in UltimaXNA.Ultima.World.WorldView.Draw(Double frameTime) in c:\UltimaXNA\dev\Ultima\World\WorldView.cs:riga 122
  in UltimaXNA.UltimaGame.Draw(GameTime gameTime) in c:\UltimaXNA\dev\UltimaGame.cs:riga 234
  in Microsoft.Xna.Framework.Game.DrawFrame()
  in Microsoft.Xna.Framework.Game.Tick()
  in Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
  in Microsoft.Xna.Framework.GameHost.OnIdle()
  in Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
  in Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
  in System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
  in System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
  in System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
  in System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
  in System.Windows.Forms.Application.Run(Form mainForm)
  in Microsoft.Xna.Framework.WindowsGameHost.Run()
  in Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
  in Microsoft.Xna.Framework.Game.Run()
  in UltimaXNA.Bootstrapper.StartEngine() in c:\UltimaXNA\dev\Bootstrapper.cs:riga 79
  in UltimaXNA.Bootstrapper.Initialize() in c:\UltimaXNA\dev\Bootstrapper.cs:riga 61
  in UltimaXNA.Bootstrapper.Main(String[] args) in c:\UltimaXNA\dev\Bootstrapper.cs:riga 28
  in System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
  in System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
  in Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
  in System.Threading.ThreadHelper.ThreadStart_Context(Object state)
  in System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
  in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
  in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
  in System.Threading.ThreadHelper.ThreadStart()}  System.Exception {System.NullReferenceException}

**Comment by ZaneDubya** [comment]
@gtozzi Thank you for submitting this. Can you tell me what was the ItemID of the Item being rendered in UltimaXNA.Ultima.World.EntityViews.ItemView.Draw? The variable will be Entity.ItemID.

**Comment by gtozzi** [comment]
@ZaneDubya it's 0x2005 and it is not on mul files. I don't know why I have an item with a not existing graphic, but it should not crash the client anyway, i suppose :D Maybe you can replace the graphic with 0x01 when not found?

**Comment by ZaneDubya** [comment]
Interesting! 0x2006 is a corpse object, I wonder if 0x2005 is something special as well.

**Comment by ZaneDubya** [comment]
@gtozzi Should be fixed as of 46ff06a4f0ef1cc8bdfa92c3240980d86e02b16b. The legacy client does not draw any items with itemid = 0x2005, so we won't draw them either. Closing as fixed - thank you for reporting and testing this!

I think it's weird that such an item exists in your database! If you search your script files, are there any references to 0x2005 or 8197?

**Comment by gtozzi** [comment]
0x2005 is a special "no beard" item.

Why and when it dropped on the ground... have no idea :)

Probably some bugged script moved it out of a decaying corpse. I have some of them around... I'll probably wipe them now, but at least they've been useful for spotting and fixing a bug ;)

**Comment by ZaneDubya** [comment]
"No beard" - that gave me a chuckle. :) Thanks for looking into it!
