### ISSUE TITLE
Sector light level affects font darkness too

### ISSUE THREAD

**Issue by robertdeclaux** [ZaneDubya/UltimaXNA#349]
![ekran goruntusu 81](https://cloud.githubusercontent.com/assets/11157985/9875503/2a70f570-5bb7-11e5-9942-d49c509daca3.png)
![ekran goruntusu 82](https://cloud.githubusercontent.com/assets/11157985/9875504/2a8e2b68-5bb7-11e5-94e6-a80d526d515c.png)

**Comment by ZaneDubya** [comment]
Fixed in 4f316f5. Closing as addressed.
