### ISSUE TITLE
Client crushing after choosing the characther

### ISSUE THREAD

**Issue by azmanomer** [ZaneDubya/UltimaXNA#350]
Error 2015-09-15 17:16:51:6209 Exception has been thrown by the target of an invocation.
Error 2015-09-15 17:16:51:6329 Unable to read settings file.  Trying backup file
Error 2015-09-15 17:16:51:6339 Exception has been thrown by the target of an invocation.
Error 2015-09-15 17:16:51:6339 Unable to read backup settings file. All settings are set to default values.
Info 2015-09-15 17:16:51:9619 Initializing UOData. Is64Bit = False
Info 2015-09-15 17:16:51:9629 Looking for UO Installation:
Info 2015-09-15 17:16:51:9639 Settings: C:\Program Files (x86)\EA Games\Ultima Online Mondain's Legacy
Info 2015-09-15 17:16:51:9649 
Info 2015-09-15 17:16:51:9649 Selected: C:\Program Files (x86)\EA Games\Ultima Online Mondain's Legacy
Info 2015-09-15 17:16:52:4279 Starting scene LoginState
Info 2015-09-15 17:16:52:4279 Initializing LoginState.
Info 2015-09-15 17:16:52:4979 Checking if file exists [C:\Program Files (x86)\EA Games\Ultima Online Mondain's Legacy\Music\Digital\Config.txt]
Info 2015-09-15 17:16:57:9032 Starting scene transition from LoginState to LoggingInState
Info 2015-09-15 17:16:57:9042 Scene transition complete.
Info 2015-09-15 17:16:57:9042 Disposing LoginState.
Info 2015-09-15 17:16:57:9052 Initializing LoggingInState.
Info 2015-09-15 17:16:57:9122 Connecting to 127.0.0.1:2593...
Info 2015-09-15 17:16:57:9142 Connected.
Info 2015-09-15 17:16:57:9392 Starting scene transition from LoggingInState to SelectServerState
Info 2015-09-15 17:16:57:9452 Scene transition complete.
Info 2015-09-15 17:16:57:9462 Disposing LoggingInState.
Info 2015-09-15 17:16:57:9472 Initializing SelectServerState.
Info 2015-09-15 17:16:57:9802 Starting scene transition from SelectServerState to CharacterListState
Info 2015-09-15 17:16:57:9812 Scene transition complete.
Info 2015-09-15 17:16:57:9812 Disposing SelectServerState.
Info 2015-09-15 17:16:57:9822 Initializing CharacterListState.
Info 2015-09-15 17:16:59:9783 Starting scene transition from CharacterListState to Null
Error 2015-09-15 17:16:59:9813 Object reference not set to an instance of an object.

im using sphere server and fresh install ml client win7 64bit in leptop my resolution is 1366x768 when i try to start it from vs2013 it gave me worldviewgump.cs line 46
![untitled](https://cloud.githubusercontent.com/assets/13722155/9879020/3f47a086-5bce-11e5-939b-5cb1d57898ae.jpg)

**Comment by ZaneDubya** [comment]
Sorry, should have realized this would be a problem. I have mistakenly limited the minimum play window resolution on first boot to 1024x768 - you have a little less than this in the y dimension because your task bar takes up some of the 768p of height. Fixed in bedc4ba9. But the resolution system is still buggy; I will revise it in the next Milestone.

**Comment by ZaneDubya** [comment]
Thank you for reporting this bug! Should be fixed! Please comment and reopen if the issue remains unfixed.
