### ISSUE TITLE
Spellbook gump issues

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#357]
1. I've noticed that when you load pages for a spellbook that is not full, there are additional blank pages at the end of the book. The book should end with the last page full, not blank (or its facing second-to-last page, if the book contains an odd number of spells).
2. Right now, the spellbook gump loads all index pages when it is first opened, and then all spell pages when the first spellpage is opened. Instead, the spellbook gump should load each page as it is requested. This will speed up opening a spellbook.

**Comment by orsi** [comment]
Number 1 is fixed, I'll attempt number 2.

**Comment by ZaneDubya** [comment]
Thanks @jorsi !
