### ISSUE TITLE
Single clicking on item only shows one of information message

### ISSUE THREAD

**Issue by robertdeclaux** [ZaneDubya/UltimaXNA#362]
![ekran goruntusu 111](https://cloud.githubusercontent.com/assets/11157985/9954595/13c098f6-5df3-11e5-90f4-097dc01e9663.png)
UltimaXNA shows only one information message but legacy client's limit is 3. (+An information message may contain more than one lines)

![ekran goruntusu 110](https://cloud.githubusercontent.com/assets/11157985/9954674/91231d64-5df3-11e5-970f-c9d1129746fe.png)
Second line of information message rendered partially.

**Comment by ZaneDubya** [comment]
No pop up messages are disaplyed when tooltips are enabled.

**Comment by ZaneDubya** [comment]
Ok! This should be fixed now. @robertdeclaux , please comment if it's still causing an issue.
