### ISSUE TITLE
Book read / write gump

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#370]
Guests should be able to read books in libraries, and add their name to the book I've locked down on my stoop.

**Comment by orsi** [comment]
I'm going to try and attempt this.

Is the client already sending data to the server when double clicking a book, or is it already registering it yet doesn't do anything with the server response to open and display it?

**Comment by ZaneDubya** [comment]
Thanks Jon! When the client double clicks on a book, the client sends a generic double-click packet. The server should respond with all the data necessary to read the book. I have not yet implemented these packets, or the data structures that would hold the book data.

**Comment by orsi** [comment]
I added the Book Header (new) and Book Pages packet and have a rough version of this working at https://github.com/jorsi/UltimaXNA/tree/book-gump.

So far I have:
![image](https://cloud.githubusercontent.com/assets/7156655/10381275/57fd7e54-6de7-11e5-92e3-aa22db557c84.png)

Compared to UO:ML Client:
![image](https://cloud.githubusercontent.com/assets/7156655/10381390/6aa1dffe-6de8-11e5-8cea-e03d043db154.png)

**Comment by ZaneDubya** [comment]
@jorsi I stole the to-do list from you comment. Theft!
- [x] Make the book text/title/author editable
- [ ] Open multiple books at once (currently closes previous book and opens new one)
- [ ] Implement client packet to send on changed text
- [ ] Add the sound effect for turning a page
- [ ] Page numbering
- [ ] Improve overall layout and formatting
- [ ] Optional: Draw different book gumps depending on book type
- [x] Books close on drag.
