### ISSUE TITLE
Pressing enter twice at character list causes crash.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#371]
Every time enter is pressed, the client attempts to load a world model. Loading a world model twice is prohibited, causing a crash. Fix: character selection should be disabled once a character has been selected.

**Comment by orsi** [comment]
Pull request sent for this issue. Just added an additional condition to see if the world was loading or not.

**Comment by ZaneDubya** [comment]
Fixed in #374
