### ISSUE TITLE
Implement OpenWebBrowser packet

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#378]
ID 0xA5: http://docs.polserver.com/packets/index.php?Packet=0xA5

**Comment by SaschaKP** [comment]
in WorldClient.cs:

``` c#
void ReceiveOpenWebBrowser(OpenWebBrowserPacket p)
        {
            if (!string.IsNullOrEmpty(p.WebsiteUrl))
            {
                try
                {
                    System.Diagnostics.Process.Start(p.WebsiteUrl);
                }
                catch (System.ComponentModel.Win32Exception noBrowser)
                {
                    if (noBrowser.ErrorCode == -2147467259)
                        UI.MsgBoxGump.Show(noBrowser.Message, UI.MsgBoxTypes.OkOnly);
                }
                catch (System.Exception other)
                {
                    UI.MsgBoxGump.Show(other.Message, UI.MsgBoxTypes.OkOnly);
                }
            }
        }
```

This complies with what is written in MSDN for browser opening, and also checks if the user can open a browser or if he doesn't have one registered in the system.

Also, even if not related, in Core/Audio/Asound.cs:

``` c#
private string m_Name;
        public string Name
        {
            get { return m_Name; }
            private set
            {
                if (!string.IsNullOrEmpty(value))
                    m_Name = value.Replace(".mp3", "");
                else
                    m_Name = string.Empty;
            }
        }
```

this is to fix an error that could be caused if the client tries to read an extension and you client insert another extension in the filename.
The original client does things this way.

**Comment by SaschaKP** [comment]
When I can understand how to create a branch and commit there, maybe it would be a lot simpler.
Because in vs2015 I cant find a way and GIT is somewhat new to me, I always use and used SVN

**Comment by ZaneDubya** [comment]
Thank you!

This is the tutorial I used to learn git: [https://www.atlassian.com/git/tutorials/using-branches](https://www.atlassian.com/git/tutorials/using-branches);

**Comment by naggie** [comment]
"Pro git" is also good https://git-scm.com/book/en/v2

**Comment by ZaneDubya** [comment]
Merged. Thanks @uoitalia !
