### ISSUE TITLE
Implement UltimaLive Live Map patches

### ISSUE THREAD

**Issue by SaschaKP** [ZaneDubya/UltimaXNA#380]
https://www.servuo.com/archive/ultima-live-map-streamer-and-editor.266/

As contained here, there is the ability to patch live the map files.

I'm trying myself to update the relative files contained in ultimaXNA, but without knowing the architecture and how-to read variables, modify tiles, etc, the learning curve is really high.

There could be various directions:
- rewrite some code and provide some interfaces or static variables to give map - tiledata - static data, leaving to me the rest of the work (I worked with praxiiz for some code of ultimalive, and I know most part of it)
- provide some lecture to facilitate other developers willing to help with the project
- write down some sample code, initial infrastructure, leaving the rest to me or someone else
- write all the code yourself

I'm for the help I could provide for this project, and I have to tell that I'm really interested.

Cheers

**Comment by SaschaKP** [comment]
of course, I'm speeching of the client itself!

**Comment by PatrikSamuelTauchim** [comment]
I just heard about this feature in classic client, but never actually seen it live. I wish to have it in UltimaXNA, since it can really make difference in the world :-)

**Comment by SaschaKP** [comment]
I'm using it constantly in the shard we own, and without this would be impossible to do extraordinary things without external patches...

Anyway, I'm just asking for some help to turn the learning curve down, I'm actually reading the code, but there are lot of differences from the naming and architecture I'm used both in UltimaLive and RunUO.

For example, how could I retrieve all maps? how can I get the actual map number and all the tiles, statictiles, landtiles? I'm just reading fast and not too much attention. surpassing this would be a facilitation.

Other thing that needs to be implemented is the livechange, now I don't know how files are locked and if there is the need to change them separately or if they are locked read-write so I can change them live, but this is another story.

**Comment by ZaneDubya** [comment]
@uoitalia This does look like a cool feature. I won't promise adding it, but I am interested in learning more. Can you identify the packets that are sent by the UltimaLive server?
