### ISSUE TITLE
Login cannot go forward after characterliststate to Null

### ISSUE THREAD

**Issue by SaschaKP** [ZaneDubya/UltimaXNA#381]
![image](https://cloud.githubusercontent.com/assets/15030741/10410008/92f5e0fc-6f34-11e5-8037-58f9beac9fea.png)

it remains locked in this loop of execution:
![image](https://cloud.githubusercontent.com/assets/15030741/10410021/dc4f2088-6f34-11e5-85ca-53baf6f5e51b.png)
continuosly filling memory, slowly.

I don't know if this is a machine or code problem, I'm using latest svn...maybe there are special requirements from the video or something else?

**Comment by SaschaKP** [comment]
Found the bug, in ultimalive we send the user map index after the login, to refresh the map in a correct way.
this is a small bug I'll take care of, expect a patch

**Comment by SaschaKP** [comment]
anyway I can't get past login and showing the map....that's strange...something is odd here :(

**Comment by SaschaKP** [comment]
tested : clean runuo version 2.2 works fine, mine customized server won't work, but the strange thing is, with the original 6.0.6.2 client it works fine.

**Comment by SaschaKP** [comment]
Resolved, it's an unknown packet issue from ObjectPropertyList.Enabled = Enabled;

Disabling the ObjectPropertyList resolves the hang of the client.

**Comment by ZaneDubya** [comment]
@uoitalia Can you propose a fix for the xna client that would solve this problem?

**Comment by ZaneDubya** [comment]
@uoitalia I'm trying to work out what fix you made. Did you disable the object property list on your server or on the client?

**Comment by SaschaKP** [comment]
You have to disable the OPL in the server --> Scripts\Misc\CurrentExpansion.cs

**Comment by ZaneDubya** [comment]
I'm glad you got it working! But it would be even better if the xna client handled the packet that was causing an error on your end. Can you paste a copy of the packet here? You should be able to find it in debug.log after you have enabled packet logging. In settings.cfg, set LogPackets=True, like so:

```
[debug]
LogPackets=True
ShowFps=True
IsConsoleEnabled=True
[/debug]
```

**Comment by ZaneDubya** [comment]
I think this has been fixed!
