### ISSUE TITLE
Game crashes when double clicking equipment slot

### ISSUE THREAD

**Issue by orsi** [ZaneDubya/UltimaXNA#383]
![image](https://cloud.githubusercontent.com/assets/7156655/10808948/6cdd8e64-7dc7-11e5-9532-acf1435f5cc7.png)

As the title states, double clicking an equipment slot seems to trigger a pick up item method, however, there is a null reference and the client crashes.

**Comment by ZaneDubya** [comment]
Fixed - thanks @jorsi
