### ISSUE TITLE
Crash on closing an npc Paperdoll

### ISSUE THREAD

**Issue by orsi** [ZaneDubya/UltimaXNA#384]
Closing an npc's paperdoll gump causes a null reference in PaperDollGump.cs when disposing the gump. Seems to be the case for any npc, but not for the own player's paperdoll.

![image](https://cloud.githubusercontent.com/assets/7156655/10958750/798331f0-833f-11e5-842b-28a30183d421.png)

**Comment by ZaneDubya** [comment]
Thanks for reporting this @jorsi - wonder what's causing it!

**Comment by greeduomacro** [comment]
To add on to this, if you close another player's paperdoll a crash occurs as well~

**Comment by ZaneDubya** [comment]
Fixed here.

https://github.com/ZaneDubya/UltimaXNA/blob/883b6ebee18b30c3830f6a0fd4df038d6a2f9b10/dev/Ultima/UI/WorldGumps/PaperDollGump.cs#L163
