### ISSUE TITLE
Crash when clicking mouse too early on login screen loading

### ISSUE THREAD

**Issue by orsi** [ZaneDubya/UltimaXNA#385]
Clicking the mouse immediately upon starting the client causes the client to crash for some reason. It seems to be a really small window for this to happen - if you wait half a second after the client opens, it doesn't crash. An easy way to recreate this bug is to start clicking on the console debug screen rapidly until the client window opens up.

![image](https://cloud.githubusercontent.com/assets/7156655/10958902/e0fef480-8340-11e5-94a3-26c1e79586cd.png)

**Comment by ZaneDubya** [comment]
Totally bizarre! Thanks @jorsi

**Comment by ZaneDubya** [comment]
@jorsi I think my fix for the previous issue you were having will have resolved this as well (hopefully!).
