### ISSUE TITLE
NullReferenceException thrown when clicking both left and right mouse button

### ISSUE THREAD

**Issue by orsi** [ZaneDubya/UltimaXNA#386]
![image](https://cloud.githubusercontent.com/assets/7156655/11493668/18b1d9aa-97c9-11e5-8365-68e51453f4bf.png)

Pretty straightforward explanation. Hold left mouse button and then click with the right mouse button, or vice versa. Client seems to be able to keep running through this exception however, but it seemed noteworthy in case no one knows about it.

I am using a touch pad, so if it turns out to be more difficult to reproduce than it sounds, it's probably related to that.

**Comment by ZaneDubya** [comment]
Hey @jorsi ! I've figured out what was going on - when the client receives a mouse up, it should clear the previous mouse down - so if you have a single button mouse that can send both left and right mouse button messages, you could potentially get input messages in this order:

Click with one finger: Left.Down
Click with two fingers: Right.Down
Touchpad sends Left.Up
Let go of two finger input: Right.Up <--- Exception.

31dee691709a5dc83a82a1306e4a47b23f298cd9 should fix this. Thanks!
