### ISSUE TITLE
The program does not start anymore: too many arithmetic instruction slots in the shaders

### ISSUE THREAD

**Issue by gtozzi** [ZaneDubya/UltimaXNA#389]
I get this error:
1>------ Build started: Project: UltimaXNA, Configuration: Debug x86 ------
1>  Building Shaders\IsometricWorld.fx -> C:\UltimaXNA\dev\bin\Debug\Content\Shaders\IsometricWorld.xnb
1>C:\UltimaXNA\dev\Content\Content\Shaders\IsometricWorld.fx : error : Errors compiling C:\UltimaXNA\dev\Content\Shaders\IsometricWorld.fx:
1>C:\UltimaXNA\dev\Content\Content\Shaders\IsometricWorld.fx : error : Compiled shader code uses too many arithmetic instruction slots (86). Max. allowed by the target (ps_2_0) is 64.

Commenting out some random code from IsometricWorld.fx is a workaround.

**Comment by fdsprod** [comment]
What kind of video card do you have?

**Comment by ZaneDubya** [comment]
@gtozzi It works on our end, so I don't know how to test this... Can you figure out if it's just the PixelShader_Hue routine? (comment out the other pixel shaders; does the error still occur)? 

@jeffboulanger That's clever! Do different graphics cards run different instructions? Is it possible that shaders which compile down to a svelte < 64 instructions on more advanced cards might be porkier on larger cards?

**Comment by gtozzi** [comment]
@jeffboulanger NVIDIA Corporation GT218 [GeForce 210](rev a2)

@ZaneDubya i think the problem is just the code being too long/complex for older video cards, not in any specific routine. To reproduce this, I think you can force compile for pixel shader 2 instead of 3 (http://prof.johnpile.com/2013/11/05/xna-compile-for-pixel-shader-3-0/), but I am not sure, since that's not really my domain: I'm mostly a backend/server developer :) If I comment out from line 107 (// Darken the color based on the ambient lighting and the normal.) to line 117 (return color;) of that routine, it works.

**Comment by ZaneDubya** [comment]
@gtozzi We're already compiling for PS20 - it's so strange that your computer has a different output than mine! Would you please check if you have XNA Game Studio 4.0 Refresh installed?

**Comment by gtozzi** [comment]
@ZaneDubya no, it is not in the installed programs list

**Comment by ZaneDubya** [comment]
@gtozzi There might be some shader compiler enhancements in the refresh - try installing it and see if the shader compiles correctly? https://www.microsoft.com/en-us/download/details.aspx?id=27599 If it does, I will be sure to add this requirement to the 'getting started' wiki...

**Comment by gtozzi** [comment]
@ZaneDubya black smoke: even with XNA Game Studio 4.0 Refresh installed it does the same

**Comment by fdsprod** [comment]
Feels a lot like some weird optimization issue.   Perhaps, for whatever reason, your machine isnt optimizing the code properly, we could probably spend time evaluating the shader, and trying to limit it's instruction set to <= 64, but thats going to take time.   Alternatively, @gtozzi you can try to up the shader version to 3.0, at the bottom of the .fx file there are parts that say 

```
compile ps_2_0 
```

change to 

```
compile ps_3_0 
```

See if that solves your problem temporarily

**Comment by gtozzi** [comment]
@jeffboulanger >C:\UltimaXNA\dev\Content\Content\Shaders\IsometricWorld.fx : error : XNA Framework Reach profile does not support pixel shader model 3.0.

Yep, by knowing how the shader works it should not be hard to shrink it down to 64 instructions. It looks like the oversized one is the PixelShader_Hue.

**Comment by fdsprod** [comment]
Ah, we only support Reach, I didn't know that.  Seems weird, to bad.  Ya I'm sure it can be optimized, ill take a stab at it since I'm on an optimization kick lately.  But may not be fore a bit, holidays coming up and all.  Got a lot going on.

**Comment by ZaneDubya** [comment]
@gtozzi Thank you for trying out my solution - sorry it didn't help. I wish we could see the output of your shader compiler.

@jeffboulanger Definitely could be optimized! I wonder if it might be possible to eliminate all the if/else statements through selecting different shaders based on the hue requirements? Six different shaders:
1. No hue, no lighting
2. Partial hue, no lighting
3. Entire hue, no lighting

4-6 would be the same three with lighting.

The extended sprite batch class already has functionality for handling different shaders.

Would that be enough to get rid of 22 (gtozzi's 86 - 64 allowed) instructions? Maybe...

**Comment by fdsprod** [comment]
Ya, if statements are expensive.  The downside to switching, is you lose some of your batching, which means more Draw calls, but depending on ordering, it may not be a big deal.

**Comment by ZaneDubya** [comment]
I'm closing this because I'm unable to replicate it - but we will fix up the shader in the future, both in the interest of speeding it up and resolving this issue for you. Hopefully that works!
