### ISSUE TITLE
Window resize / maximize support.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#39]
As a player, I want to be able to change the dimensions of the Ultima Online client window.
1. Like the classic client, UltimaXNA should start at a resolution of 640x480. While the client is logging in, it is locked to this resolution.
2. Once in the world, the player should be able to resize the window at any time. This includes the ability to maximize / restore the window.
3. When the client enters the world, the client should resize / move itself to the last position it occupied when playing in the world.

**Comment by ZaneDubya** [comment]
Should be working in branch vodacek-windowing. Window sizing works well, and the client restores the maximized window (if it was maximized) when returning to the world. I kept @jeffboulanger's larger login gumps - the legacy login gumps look better with a little extra space on the bottom and right. Request QA.

**Comment by ZaneDubya** [comment]
![screen-shot-2015-04-22-at-10 31 08-am](https://cloud.githubusercontent.com/assets/7041719/7278450/2eaba3be-e8db-11e4-9b51-ecbfdf69ead9.jpg)

**Comment by Vodacek** [comment]
waw, that looks awesome! I have now so much work for school and our shard, but I am watching the news :-) God job! 

---
