### ISSUE TITLE
Very long htmlgumps are causing infinite loop

### ISSUE THREAD

**Issue by denizsokmen** [ZaneDubya/UltimaXNA#391]
IN HtmlDocument.cs, line 444. It gets stuck forever because for some reason it's always trying to break the words and the following "i--;" line causes the for loop to work infinitely.

**Comment by ZaneDubya** [comment]
Can you post the text of the gump that is causing this issue?

**Comment by ZaneDubya** [comment]
This also happens at private void HtmlElement.LayoutElements_BreakWordAtLineEnd(List<AElement> elements, int start, int lineWidth, List<AElement> word, int wordWidth, int styleWidth)

**Comment by ZaneDubya** [comment]
Fixed - I think - in the new book gump pr.
