### ISSUE TITLE
an error SingleItemToContainer packet and VendorBuyGump on Sphereserver

### ISSUE THREAD

**Issue by msx752** [ZaneDubya/UltimaXNA#396]
i created a new npc " for example: Tailor", after that i said "buy" later i received very long an error (i think its verdor item list but why i get an error ?).after that i getting same error on VendorBuyGump" :https://github.com/ZaneDubya/UltimaXNA/issues/384 . when i jumped to "m_OKButton.MouseClickEvent" i getting a transparent menu.
and this: https://github.com/ZaneDubya/UltimaXNA/issues/348
![error1](https://cloud.githubusercontent.com/assets/11164838/12237084/9da05128-b885-11e5-89d0-adf6a1ee9a5a.png)
![error2](https://cloud.githubusercontent.com/assets/11164838/12237090/a2e68f08-b885-11e5-8778-996063a4b83e.png)

**Comment by ZaneDubya** [comment]
And, oddly, the vendor buy background isn't showing up...

**Comment by ZaneDubya** [comment]
I'm guessing this is caused by a similar problem to what was causing the incorrect packet length for the features packet.

**Comment by msx752** [comment]
i resolved with two important fix :+1:  #348(fixed) ,,  #384(fixed:with #398)

**Comment by MSAlih1** [comment]
when i sended custom clientVersion 6.0.6.2. "SingleItemToContainer error" was resolving
