### ISSUE TITLE
Mouse button input should match Classic Client.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#40]
As a player, I expect UltimaXNA's single/double click handling to match the same functionality in the classic client. As part of this Issue, the client should be able to choose which mouse button is the 'command' input button, and which is the 'move' input button.

By default, the values should be:

**LMB: Command button.**
- Click on...
  - Ground: No effect.
  - StaticItem: Pop-up with name of clicked item.
  - Item [FN1]: Request Context-Menu for the targeted Item.
  - Mobile: Request Context-Menu for the targeted Mobile.
- Click-Drag on... [FN2]
  - Ground: No effect.
  - StaticItem: No effect.
  - Item: Attempt to pick up.
  - Mobile: Create new mini-mobile-status Gump for the targeted Mobile.
- Double-Click on...
  - Ground: No effect.
  - StaticItem: No effect.
  - Item: Send Double-Click packet for the targeted Item.
  - Mobile: Set LastTarget == targeted Mobile. If in WarMode, set Attacking == true.

**RMB: Move button.**
- Click: If not facing direction of Click, turn to face that direction. If already facing, move one tile.
- Click-Hold: turn to face direction and move in the specified direction.

FN1: Note that 'Items' are all Items that are not StaticItems.
FN2: Click-Hold for .5 seconds is equivalent to Click-Drag.

**Comment by ZaneDubya** [comment]
Please correct me if I'm wrong! @Eskymak @Vodacek

**Comment by Vodacek** [comment]
Left click on Item that have Context menu opens it.

**Comment by ZaneDubya** [comment]
Implemented, in good part, in PR #51.

Remaining questions:

Is there any situation where holding down the LMB on any object would cause any output?

Do we treat corpses different from containers in any way?

**Comment by ZaneDubya** [comment]
Ok! Everything is implemented except for mini-status gumps, which I won't add until after Milestone 0.4

**Comment by ZaneDubya** [comment]
And Context-Menus. Also queued for past Milestone 0.4
