### ISSUE TITLE
ChatControl not registered

### ISSUE THREAD

**Issue by ghost** [ZaneDubya/UltimaXNA#401]
Server version RunUO 2.3r987
Client version 7.0.18.0
After logging with selected character Im getting following error in console:
Error 2016-01-30 11:56:16:9257 Attempted to get service service of type UltimaXNA.Ultima.UI.WorldGumps.ChatControl, but no service of this type is registered.
And then game stops on message "Entering Britannnia..."

**Comment by ghost** [comment]
Sorry for inconvenience. Finally, I found out that UltimaXNA supports only one version of client

**Comment by ZaneDubya** [comment]
@Pishka I think we can still fix this issue! Thank you for reporting.

**Comment by ZaneDubya** [comment]
Woah. If you write the text "Fixes #xxx" in a commit message, it automatically closes the issue.

Hopefully it's fixed, then!
