### ISSUE TITLE
Rubberbanding on diagonal movement 'by' impassable tiles.

### ISSUE THREAD

**Issue by mhague** [ZaneDubya/UltimaXNA#402]
Walking Left, Right, Up or Down should almost always cause direction change when needed.

Example, currently walking in this way into the side of a building will cause you to change to cardinal direction, and follow the wall.
This works until you arrive at a corner, in which case you will see rubberbanding as the client thinks it is a valid move.

**Comment by ZaneDubya** [comment]
@mhague I think that players with gamemaster access level on RunUO can walk through impassable corners (see https://github.com/runuo/runuo/blob/81e5f9845931eeecc26d608b5c8e954ece194235/Scripts/Engines/Pathing/FastMovement.cs#L428).

Is there some way I can detect on the client whether the access level has been set to game master? If not, I think I'll follow your suggestion and limit diagonal movement regardless of access level.

**Comment by SaschaKP** [comment]
If Three are obstacles left&right but not in diagonal no one Can Pass.  Even game Masters

Inviato da Samsung Mobile.

<div>-------- Messaggio originale --------</div><div>Da: Zane Wagner notifications@github.com </div><div>Data:01/02/2016  13:08  (GMT+01:00) </div><div>A: ZaneDubya/UltimaXNA UltimaXNA@noreply.github.com </div><div>Cc:  </div><div>Oggetto: Re: [UltimaXNA] Rubberbanding on diagonal movement 'by' impassable
  tiles. (#402) </div><div>
</div>@mhague I think that players with gamemaster access level on RunUO can walk through impassable corners (see https://github.com/runuo/runuo/blob/81e5f9845931eeecc26d608b5c8e954ece194235/Scripts/Engines/Pathing/FastMovement.cs#L428).

Is there some way I can detect on the client whether the access level has been set to game master? If not, I think I'll follow your suggestion and limit diagonal movement regardless of access level.

**Comment by mhague** [comment]
Did not know that about GM access.

Agree it should be limited.  It's especially apparent when walking diagonally through areas with lots of 1 tile blockers (i.e. the forest?) where players often walk diagonals to avoid getting stuck on rocks and trees.

**Comment by mhague** [comment]
I don't know if this is still implemented in runuo, but there is this to check access:

http://www.docs.polserver.com/packets/index.php?Packet=0xF0

**Comment by ZaneDubya** [comment]
@mhague That's an interesting find! I'll go ahead and disable diagonal movement through 'impassable' corners, and will close this issue when I've done so. Thanks guys!

**Comment by frozenblit** [comment]
Just to chime in, POL also blocks diagonal movements (no GM check, I wasn't aware that the classic client allows this freedom for GMs :)). Is the 0xF0 packet implemented anywhere? As far as I know, the  original client only tests whether the char has a GM graphic to enable special features.

**Comment by ZaneDubya** [comment]
> As far as I know, the original client only tests whether the char has a GM graphic to enable special features.
> @frozenblit That is interesting! Is there a single GM body ID or multiple IDs?

**Comment by frozenblit** [comment]
The only ID seems to be 0x03DB (at least that's the only one POL allows passing through doors, besides ghosts :D). The difference between couns/gm/seers/etc should be only their color.

**Comment by ZaneDubya** [comment]
Fixed in ccb0585; see #419 for more comments.
