### ISSUE TITLE
Issue Loading

### ISSUE THREAD

**Issue by Immortel71** [ZaneDubya/UltimaXNA#403]
![xnabug3](https://cloud.githubusercontent.com/assets/17111748/12874226/a0418ee2-cd9d-11e5-8057-e47053b0f303.png)

Got this errors trying to load, any hints ?

**Comment by ZaneDubya** [comment]
@Immortel71 Would you post your entire debug.log file? Thank you!

**Comment by ZaneDubya** [comment]
For all I know, this has already been fixed in the most recent set of commits. Can't address it without more information :(
