### ISSUE TITLE
Ethereal Mounts Unable to be Mounted/Etc.

### ISSUE THREAD

**Issue by greeduomacro** [ZaneDubya/UltimaXNA#405]
Ethereal Mounts seem to not be usable in the context that there is no casting animation, nor is there a speed increase after getting on the ethereal, nor does the player show that they are on an ethereal mount.

**Comment by ZaneDubya** [comment]
Tested on ML (4.x.x.x client data set) and RunUO 2.6. I see the casting animation, the mounted animation, and speed is as expected. Closing as fixed. Please comment if this continues to be an issue for you.
