### ISSUE TITLE
Sound Spam

### ISSUE THREAD

**Issue by greeduomacro** [ZaneDubya/UltimaXNA#406]
Not a huge issue but would be a nice quality of life change to add a delay between the spamming of sounds, especially in the context of mobiles. If you compare Ultima XNA with the 2D client by say having 50 dragons fight a champion at the same time you will see what I mean. That is to say the sounds are pretty unpleasant in the UXNA client compared to the 2D client because there is a delay on the time that the dragons could make a sound for the 2D which doesn't exist in UXNA.

**Comment by ZaneDubya** [comment]
Fixed in #435, minimum one second spam delay between sounds requested to play by server.
