### ISSUE TITLE
0xf0 packet support

### ISSUE THREAD

**Issue by Vlek** [ZaneDubya/UltimaXNA#407]
I've had to search long and far for a server that is still using client versions <= ML, and, when I did find one, I got tossed an error that UXNA didn't understand the extended information (0xf0) packet.

**Comment by ZaneDubya** [comment]
I think I found what you're talking about here: https://github.com/runuo/runuo/blob/d038571b412188c2f4416f29846f11275c1e7bcb/Scripts/Misc/Assistants.cs

**Comment by ZaneDubya** [comment]
That's bizarre. I'm pretty sure I made those label changes, not @Vlek . :|

**Comment by ZaneDubya** [comment]
Added in f5105c4e78aa454820a39d06de53f4debc6f047e.
