### ISSUE TITLE
War Mode Does not Respond Properly

### ISSUE THREAD

**Issue by greeduomacro** [ZaneDubya/UltimaXNA#415]
You double click the mobile that you want to attack and like, 99% of the time you don't actually attack and also if you double click on the health bar of another player/mobile while in war mode you do not attack that player or mobile.

**Comment by PatrikSamuelTauchim** [comment]
While working on #434, I had no issues attacking mobiles. Can someone verify if this is still an issue and if so, provide more details?

**Comment by ZaneDubya** [comment]
@greeduomacro @PatrikSamuelTauchim I agree with Patrik, this appears to be fixed. Thanks for testing it!
