### ISSUE TITLE
Double Clicking on Health Bars of Other Players Does not Bring up Their Paper Dolls

### ISSUE THREAD

**Issue by greeduomacro** [ZaneDubya/UltimaXNA#416]
If you drag someone's health bar and then double click it, it does not bring up their paperdoll.

**Comment by ShiniHatsune** [comment]
also something else that is similar , double clicking (left click) other players/mobiles health bars while being in war mode doesn't attack them.

**Comment by PatrikSamuelTauchim** [comment]
@greeduomacro Should be implemented with #434
@ShiniHatsune I will take look on that

**Comment by PatrikSamuelTauchim** [comment]
Completed in #434

**Comment by ZaneDubya** [comment]
Thanks Patrik!
