### ISSUE TITLE
Using Ctrl + Shift Shows all Objects

### ISSUE THREAD

**Issue by greeduomacro** [ZaneDubya/UltimaXNA#417]
The way Ctrl + Shift is supposed to work (I believe) is that it should only show movable objects and mobiles. Currently it shows all objects regardless of whether or not the object is movable. Also you can see the items on your paperdoll (even your hair/etc).

**Comment by ZaneDubya** [comment]
That's kinda funny. :) Should be relatively easy to fix, though.

**Comment by ZaneDubya** [comment]
Ok! This is looking good. I've addressed both of the issues you've identified. One remaining issue is that existing player overhead labels are overwritten by Ctrl+Shift - I can fix that in another issue.
