### ISSUE TITLE
Corner cutting and rubber banding. 

### ISSUE THREAD

**Issue by greeduomacro** [ZaneDubya/UltimaXNA#419]
I'm not precisely sure what it is but I think it's something like, trees count as mobiles perhaps? If a staff member runs right next to a tree they can run around the tree but if a player runs around a tree they cannot run around the tree. I almost wonder if trees are being counted as mobiles or something? Not sure...

**Comment by SkavenCleric** [comment]
You can't 'cut corners' in Ultima, yet this client allows it, resulting in your character getting 'stuck'.

http://prntscr.com/aemj3k

**Comment by ZaneDubya** [comment]
Cutting corners is allowed by default for admins on RunUO - which is my test environment - so I completely missed this issue. It would be a fairly easy fix though:

I would allow the client to cut corners b default, and upon having the corner move rejected once, maybe twice by the server, I would turn off corner cutting until the next log in.

**Comment by mhague** [comment]
This is a direct result of and duplicate of #402

**Comment by ZaneDubya** [comment]
I just logged on to my test server with a non-admin client - I agree, this is really frustrating. I'll see if I can't whip something up for it...

**Comment by ZaneDubya** [comment]
Should be fixed in ccb0585. Unfortunately, I could not think of an easy way to allow both admin-style corner cutting and player-style no-corner movement, so I just disabled it by default. You can enable admin-style corner cutting movement with Settings.UltimaOnline.AllowCornerMovement = true.
