### ISSUE TITLE
World items (doors, etc) do not reappear when the client walks several screens away and then returns.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#42]
As a player, I expect that all items will be loaded correctly from the server.

Try logging in next to a door or set of double doors. Walk several screens away. Then walk back to the original login point. The doors will be missing. What gives?

**Comment by Vodacek** [comment]
confirmed, I have the same issue
 

---

**Comment by ZaneDubya** [comment]
I believe I have fixed this bug in branch statics-dispose-and-better-headers, but cannot test until Monday. If someone has a chance, could they checkout that branch and see if it has fixed the bug? Thanks!

**Comment by Vodacek** [comment]
I tried that branch and it is now ok, except when I go through teleporter to another location game crashes. EntityManager.GetPlayerObject() returns null
I master branch is this ok.

**Comment by ZaneDubya** [comment]
Thank you for checking - I'll take another look tonight.

**Comment by ZaneDubya** [comment]
Can you replicate the crash with the tele command?

E.g.

[tele cove

[tele yew

**Comment by ZaneDubya** [comment]
I think I've fixed this in 1853729b0011114f572e6dc7eb8f7e5eb757d036.

**Comment by Vodacek** [comment]
yes you are :-) good job!

**Comment by ZaneDubya** [comment]
Fixed in #44
