### ISSUE TITLE
Moving Between Facets Causes all Items to Disappear from Backpack

### ISSUE THREAD

**Issue by greeduomacro** [ZaneDubya/UltimaXNA#420]
If you switch from Trammel to Felucca, etc etc then all of your items visually disappear from your backpack and you are forced to relog to see them again.

**Comment by ZaneDubya** [comment]
Interesting! This should be easily fixable.

**Comment by ZaneDubya** [comment]
Confirmed, this is still happening...

**Comment by ZaneDubya** [comment]
@greeduomacro I believe this is fixed in 764ad3c. Please let me know if this is not the case.
