### ISSUE TITLE
Snake Corpses Cause a Crash

### ISSUE THREAD

**Issue by greeduomacro** [ZaneDubya/UltimaXNA#422]
For some reason snake corpses specifically cause a crash for the client. _shrugs_

**Comment by ZaneDubya** [comment]
So true. And so bizarre. I spent five minutes refreshing my memory regarding how the body translator works -- oof, this source code is a real beaut! So poorly organized! --- and it looks like the snake body definition index (in anim.idx) doesn't match the typical Animal body type.

... but looking at InsideUO, it looks like a Snake is a monster type, not an animal! Let me change that in the body def table...

**Comment by ZaneDubya** [comment]
Yup, that fixed it! Thanks @greeduomacro
