### ISSUE TITLE
Canceling a pet command that require a target cause all these functions to stop working

### ISSUE THREAD

**Issue by ShiniHatsune** [ZaneDubya/UltimaXNA#426]
if you press escape to cancel a target while using a pet command that require a target such as all kill , transfer , remove friends , add friends ect. these functions become not usable until you relog.

x-x

**Comment by ZaneDubya** [comment]
Sad! I'll see if I can't treat your pets better.

**Comment by ZaneDubya** [comment]
Fixed. Thanks for reporting @ShiniHatsune !
