### ISSUE TITLE
Client doesn't exist

### ISSUE THREAD

**Issue by jmenashe** [ZaneDubya/UltimaXNA#428]
The readme states that the client can be downloaded from here: http://games.mirrors.tds.net/pub/ea-games/uo/uoml_setup.exe

The link is broken. Given that only one particular version is supported, the readme should point to a safe, legitimate, and reliable link for the installer.

**Comment by fdsprod** [comment]
http://download.cnet.com/Ultima-Online-Mondain-s-Legacy-client/3000-7540_4-10432237.html should work

**Comment by fdsprod** [comment]
Leaving open so readme is updated

**Comment by PatrikSamuelTauchim** [comment]
Done, can be closed.
