### ISSUE TITLE
Client crash after

### ISSUE THREAD

**Issue by Lemonter** [ZaneDubya/UltimaXNA#431]
Client crash after choose character
error say  array is out of bounds 
can some one help me?
[debug.zip](https://github.com/ZaneDubya/UltimaXNA/files/464771/debug.zip)

![crash](https://cloud.githubusercontent.com/assets/22106392/18401842/a67aae8e-76ed-11e6-9e80-65eaabfd5ed4.png)

**Comment by Lemonter** [comment]
UPDATE
i have changed array limits from 0x4000 to 0x12000 and client STARTS!! but i have new problems
![paperdoll](https://cloud.githubusercontent.com/assets/22106392/18405200/0b5450b8-7701-11e6-8f9b-c7b22f932d00.png)

 all tiles goes crazy salad and crash when i try look paperdoll 
it say's error Object reference does not point to an object instance 

[debug.zip](https://github.com/ZaneDubya/UltimaXNA/files/464978/debug.zip)

it's not all, if i try to connect to another character in hause at city still have array bounds error, when extend to 0x32000 had new error The destination call generated an exception
[debug.zip](https://github.com/ZaneDubya/UltimaXNA/files/464985/debug.zip)
![city](https://cloud.githubusercontent.com/assets/22106392/18405408/c93dde72-7702-11e6-83d3-eacdfb7aebf3.png)

**Comment by SaschaKP** [comment]
are your "Items" bound to 0x4000 (pre-HS/SA) or post (0x8000)?

**Comment by ZaneDubya** [comment]
I've looked into this issue, and I'm fairly certain that this is caused by using client data set that we do not support. I'll look into supporting more recent data sets in the future - for right now, I want to focus on getting the client working with ML-era data.
