### ISSUE TITLE
Support for new client data format.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#46]
Just putting this on the radar: does anyone know what changes would be necessary to support the latest client data format?

**Comment by robertdeclaux** [comment]
I think your old decision, "no support for the new data format" was right.
No one likes UO as it is, everyone likes it like it was. Major versions
like 2.0.3 or 4.0.0c or at least mondains legacy must be targetted first.

**Comment by ZaneDubya** [comment]
Thanks for keeping me focused. Haha.

I brought this up because the client link on the wiki no longer works (it now downloads the latest version, not 7.0.24). Is there a working link out there for a vanilla ML client?

**Comment by robertdeclaux** [comment]
:))
http://games.mirrors.tds.net/pub/ea-games/uo/uoml_setup.exe
20 Mar 2015 22:33 tarihinde "Zane Wagner" notifications@github.com yazdı:

**Comment by ZaneDubya** [comment]
Thanks @robertdeclaux. Closing this issue.
