### ISSUE TITLE
Implement Multi objects (houses, etc.) and targeting.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#52]
As a player, I want to be able to place houses using deeds, and see placed houses on the map.

**Comment by ZaneDubya** [comment]
I think the best way to do this will be to have the Multis add their constituent items to all active map blocks when initially loaded. The MapBlocks should also inform all active Multis when they are loaded into memory - the multis would respond by checking to see if any of their items are in those blocks, and load them as appropriate.

**Comment by ZaneDubya** [comment]
Started work in branch multis.

**Comment by ZaneDubya** [comment]
Multis implemented! All that's left to do is multi targeting. Work continuing in branch multis.

**Comment by ZaneDubya** [comment]
Merged multi code with master. Code should allow for placement of multis, and multis should display in the world once placed.

Features not implemented:
- Custom housing.
- Preview of multi placement while multi targeting cursor is active.

**Comment by robertdeclaux** [comment]
Running as described. :+1:
