### ISSUE TITLE
Czech font rendering issue

### ISSUE THREAD

**Issue by Vodacek** [ZaneDubya/UltimaXNA#59]
Font rendering is not correct in gumps HTML elements (body tags). Also czech capital letters are rendered in wrong location, see picture:
![font-rend](https://cloud.githubusercontent.com/assets/2104849/6777801/577b0bfe-d14d-11e4-916e-039dc81861ef.png)
Same issue exists in GumpStudio tool I suspect that this can be caused by ultima.dll.

**Comment by Vodacek** [comment]
Problematic letters are: ČŠŘÁÍÉÓÚŮÝŤĽ (all right ľ is not czech but for our slovak folks... :-)) thank you Mr. Jan Hus!

**Comment by ZaneDubya** [comment]
Can you tell if these characters are being rendered with UnicodeFont or AsciiFont?

**Comment by Vodacek** [comment]
unicode

**Comment by ZaneDubya** [comment]
Check out 0bfdf722482d495ace7c0de2a95365963579077f - it looks good to me.

**Comment by Vodacek** [comment]
for me too, thank you!
 

---
