### ISSUE TITLE
Client is not showing dialogs

### ISSUE THREAD

**Issue by robertdeclaux** [ZaneDubya/UltimaXNA#6]
Client is not showing dialogs, fully working dialog system needed. (tested on sphere server, wanted to work on sphere server)

I meant gumps, an example double clicking on runebook (with 2.0.3 origin client first ss, with ultimaxna secound ss)
![ekran goruntusu 9](https://cloud.githubusercontent.com/assets/11157985/6592326/7493ea66-c7d5-11e4-8646-53d868dd4d08.png)
![ekran goruntusu 7](https://cloud.githubusercontent.com/assets/11157985/6592311/3d56002a-c7d5-11e4-9cfa-e3fccc57a68e.png)

**Comment by ZaneDubya** [comment]
@robertdeclaux Can you edit the original submission to include an example of what you mean by 'dialogs', and, if possible what steps should be taken to replicate the issue?

**Comment by robertdeclaux** [comment]
I meant gumps, an example double clicking on runebook (with 2.0.3 origin client first ss, with ultimaxna secound ss)
![ekran goruntusu 9](https://cloud.githubusercontent.com/assets/11157985/6592326/7493ea66-c7d5-11e4-8646-53d868dd4d08.png)
![ekran goruntusu 7](https://cloud.githubusercontent.com/assets/11157985/6592311/3d56002a-c7d5-11e4-9cfa-e3fccc57a68e.png)

**Comment by ZaneDubya** [comment]
@robertdeclaux  Thanks for figuring out what packet was not be handled! I think this will take a while to solve: we'll need to implement each of Ultima Online's interfaces (the rune book, the spell book, etc) as its own client-side gump, and open it when the proper packet is received.

**Comment by robertdeclaux** [comment]
I do not use client's hardcoded runebook gump
if it exist. Is it too much work to implement client-side gumps for
everyting menus etc. to complete? If you can make it i will use it on my
server as a beta client so we can take more bug reports and tests. thank you

2015-03-13 17:42 GMT+02:00 Zane Wagner notifications@github.com:

**Comment by ZaneDubya** [comment]
@robertdeclaux Are you talking about loading in new clientside gumps from an external file? I would be interested in seeing the file format of those gump files.

With regards to adding these features, I believe it would be best to open an issue for each clientside gump, and include an example of what the gump should look like in the classic client, and perhaps a description of how the gump works from a User perspective, or a link to a website that contains the same information. So, for example, the issue would be "Implement Runebook" with a picture of the Runebook and a link to http://stratics.com/skill-guides/skills-and-professions/magery-essay/rune-books.

**Comment by robertdeclaux** [comment]
No i mean for example when you double click on houses sign it opens housing
system (adding friend to house etc) this dialogs are not shown in your
client on sphere server. Not this only, all of the server sided dialogs, Did you code it? Is it running on runuo?
16 Mar 2015 19:08 tarihinde "Zane Wagner" notifications@github.com yazdı:

**Comment by robertdeclaux** [comment]
@ZaneDubya i gave an confusing example with runebook. On my server, runebook has server sided dialog not a special hardcoded in client dialog. I will add another console screenshots of other dialogs server sided. They are not giving any error but not displayed.

**Comment by Vodacek** [comment]
yes, some gumps (book for example) are hardcoded in client

---

**Comment by ZaneDubya** [comment]
I can confirm that house gumps are visible using RunUO (although obviously not complete, as the client does not yet handle some of the gumplings that comprise that gump).

![house-gump-visible](https://cloud.githubusercontent.com/assets/7041719/6854517/ccd7a62c-d3bf-11e4-8a11-ec26f9614e4b.png)

**Comment by ZaneDubya** [comment]
Fixed.
