### ISSUE TITLE
Arrow keys player movement

### ISSUE THREAD

**Issue by Vodacek** [ZaneDubya/UltimaXNA#61]
Like in original client we need to support limited movement using arrow keys.

**Comment by ZaneDubya** [comment]
Let's get this done!

**Comment by robertdeclaux** [comment]
:+1:  it sounds like macros coming

**Comment by ZaneDubya** [comment]
I think those are a long way away yet ;)

This issue addressed in 50ceabc83ee37975b881593e3d5a6dba78e7870f.

**Comment by robertdeclaux** [comment]
Feature confirmed.

**Comment by ZaneDubya** [comment]
@robertdeclaux Thank you!

**Comment by robertdeclaux** [comment]
Feature implemented better than the default client, using combination of arrow keys goes the all of the 8 directions.
