### ISSUE TITLE
Text render priority

### ISSUE THREAD

**Issue by robertdeclaux** [ZaneDubya/UltimaXNA#66]
If text is longer, some tiles cut the text.
![ekran goruntusu 11](https://cloud.githubusercontent.com/assets/11157985/6822474/c402d292-d2e8-11e4-9577-1ee82e8ae8e3.png)

**Comment by ZaneDubya** [comment]
Ah. The Overheads are being displayed on the same 'z' level (z-buffer / rendering depth) as the tile that spawned it. One possible solution would be to 'queue' all the OverheadViews that are drawn, and then dequeue all of them after the world has finished drawing.

**Comment by ZaneDubya** [comment]
Should be fixed in 33d38e498c31ed47526020f86039673814242fd1.

**Comment by robertdeclaux** [comment]
Fix confirmed.

**Comment by ZaneDubya** [comment]
Thanks @robertdeclaux !
