### ISSUE TITLE
Duplicate text rendering

### ISSUE THREAD

**Issue by robertdeclaux** [ZaneDubya/UltimaXNA#67]
If i message "asd" then "asd" again only just one "asd" shows up.

**Comment by ZaneDubya** [comment]
Fixed in f56c89501c1a5c9cb9df6517fdc3f4c4cd72c0f9.

**Comment by robertdeclaux** [comment]
fix confirmed.

**Comment by ZaneDubya** [comment]
@robertdeclaux Thanks!
