### ISSUE TITLE
Walking behaviour like default client

### ISSUE THREAD

**Issue by robertdeclaux** [ZaneDubya/UltimaXNA#68]
Playing with default client if i right click with cursor placed there, it will go through the red lines.
But UltimaXNA denies moving
![ekran goruntusu 17](https://cloud.githubusercontent.com/assets/11157985/6829178/5f424a04-d31a-11e4-9355-d8c0f2e698c4.png)

**Comment by ZaneDubya** [comment]
Addressed in 278a486665056190b385de36132d242c7bb9c5ab.

**Comment by PatrikSamuelTauchim** [comment]
Can you also make possible to rotate the character without actual movement?
In classic client, key press short enough just changing direction of character. Opposite to that, if you holding mouse button pressed and moving cursor around character, makes it just rotate at one spot.
- single key press - rotation change
- holding down key/mouse button - movement

**Comment by ZaneDubya** [comment]
@Eskymak that's definitely possible - I wonder how much tinkering with the Movement class it would take...

**Comment by ZaneDubya** [comment]
Added ability to change facing, with both mouse and keyboard, in 387c7de8148288be3fa950c34e82f5bc41ecc773. Did I do it correctly?

**Comment by robertdeclaux** [comment]
It's nearly same as default client, just a missing animation frame. In default client while changing face direction it shows this frame too, not a direct change.

![1](https://cloud.githubusercontent.com/assets/11157985/6871994/101d45e6-d4af-11e4-899a-4b66a6573dda.png)

**Comment by robertdeclaux** [comment]
As i see here the first screen shot in this thread from XNA, and the second one from the original client. Hues seems a little bit different.

**Comment by ZaneDubya** [comment]
Hues are a separate issue entirely!

The frame you're mentioning is the first frame of the move animation: the client queues up the animation for movement, in case the player decides to move that way. I don't think the extra frame is important. The XNA client should match the features of the legacy client, not every little stylistic choice. :)

**Comment by ZaneDubya** [comment]
Closing as complete.
