### ISSUE TITLE
Splitting / merging piles of objects.

### ISSUE THREAD

**Issue by robertdeclaux** [ZaneDubya/UltimaXNA#74]
Piled objects must be divisible as they picked up.

![ekran goruntusu 25](https://cloud.githubusercontent.com/assets/11157985/6880527/55b7567e-d53f-11e4-9aec-a9adab1b3829.png)

**Comment by ZaneDubya** [comment]
Also should be able to drop objects onto other objects.

**Comment by robertdeclaux** [comment]
I can merge two bandages on floor but on my backpack it doesn't leave item on a item. (tested on sphereserver, but i think client denies to free item)

**Comment by ZaneDubya** [comment]
Cool, let's do this.

**Comment by ZaneDubya** [comment]
Implemented in #165.
