### ISSUE TITLE
Moving effects display.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#78]
Right now, MovingEffects do not actually move through the world - they just despawn. They need to animate moving from source to target. Question: at what speed should they move?

**Comment by ZaneDubya** [comment]
First pass in f512d47e81f5418463b6b96b82454eb8a1cab13c.

**Comment by ZaneDubya** [comment]
Implemented in 1107ec4a014b3387d9e8f18f067a81baf419254c.

**Comment by ZaneDubya** [comment]
Implemented in PR #90! Moving effects (fireballs, etc) should be visible in the world now.

**Comment by robertdeclaux** [comment]
Magic arrow, fireball, energy bolt animations working good.

**Comment by ZaneDubya** [comment]
Thank you! Closed as finished.
