### ISSUE TITLE
Targeting does not respond with sphereserver emulator

### ISSUE THREAD

**Issue by robertdeclaux** [ZaneDubya/UltimaXNA#8]
After using command ".add c_horse_gray"
If i target on ground nothing happens, if i target on my character on first click nothing happens after second click it shows "Targeting cancelled.".

**Comment by ZaneDubya** [comment]
@robertdeclaux:

This works on RunUO. I noticed from your other opened issue that you use sphereserver. I don't intend to target any other servers until the client is feature complete (if that ever occurs). If you would like to debug this:

When initially writing the client, I would often be running RunUO in one visual studio window, and UltimaXNA in another. That way, I could debug exactly how the client and server were interacting. I recommend doing this with your server.

When the user targets something - either land or an entity - the client eventually calls WorldInput.onTargetingButton(AMapObject worldObject). It then sends the correct kind of packet (either TargetObjectPacket or TargetXYZPacket) to the server. I would check what is happening on the server when it receives these packets.

**Comment by robertdeclaux** [comment]
Target request then target ground behavior comparison UltimaXNA and Default client
Original Client
Server -> Client
6C 01 00 00 01 E9 00 00 00 00 00 00 00 00 00 00
00 00 00

Client -> Server
6C 01 00 00 01 E9 00 00 00 00 00 15 3D 04 98 00
00 00 00

UltimaXNA
Server -> Client
6C 01 00 00 01 E9 00 00 00 00 00 00 00 00 00 00
00 00 00

Client -> Server // no 01 E9
6C 01 00 00 00 00 00 00 00 00 00 15 3D 04 98 00
00 00 00

Client -> Server // target cancel packet?
6C 00 00 00 00 00 03 00 00 00 00 00 00 00 00 00
00 00 00

**Comment by ZaneDubya** [comment]
@robertdeclaux Take a look at 19efbd24d21f373a37c0b5715b331e54d4a80866 (pushed to master). Is it fixed?

**Comment by robertdeclaux** [comment]
default client
6C 01 00 00 01 E9 00 00 00 00 00 15 3D 04 98 00

ultima xna
6C 01 00 00 00 00 00 00 00 00 00 15 3D 04 98 00
if we can send 01 E9 too it will be completely fixed

**Comment by ZaneDubya** [comment]
Looking at various UO protocol guides, there seems to be some disagreement as to what that value is.

It could be the Serial of the targeting mobile (the player's serial). [1] Is your serial 0x000001E9?
Or is could be the ID of the Cursor. [2]

References:
[1] http://necrotoolz.sourceforge.net/kairpacketguide/packet6c.htm
[2] http://docs.polserver.com/packets/index.php?Packet=0x6C

**Comment by ZaneDubya** [comment]
For reference, my default client sends this message when targeting:

11:44:48.6312: Client -> Server 0x6C (Length: 19)
0000   6C 01 00 00 00 1B 00 00  00 00 00 09 49 04 A6 00   l...........I...
0010   05 00 00                                           ...

**Comment by robertdeclaux** [comment]
I think its cursor id, on mobile now i will check when got home.
24 Mar 2015 18:43 tarihinde "Zane Wagner" notifications@github.com yazdı:

**Comment by ZaneDubya** [comment]
As it turns out, it's a cursor ID that is unique to the target packet. I've implemented this and pushed it to Master. Should be fixed!

**Comment by robertdeclaux** [comment]
Wow. So quick :+1: , to remind we can rollback to old target cancel function
