### ISSUE TITLE
Shadows for mobiles.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#80]
As a player, mobiles without shadows seem to be moving in the air. Adding shadows would make it clear that the mobiles are, in fact, on the ground.

**Comment by ZaneDubya** [comment]
Protip: the legacy client only uses the base body sprite of a model to project a shadow. So clothes, weapons, hats, etc. don't project shadows; only the body sprite does.

**Comment by ZaneDubya** [comment]
Implemented early! Moving to M0.7.

**Comment by robertdeclaux** [comment]
Awesome!
