### ISSUE TITLE
Incorrectly hued cursor in Trammel.

### ISSUE THREAD

**Issue by PatrikSamuelTauchim** [ZaneDubya/UltimaXNA#87]
Non-warmode cursor is dark grey instead of gold, compared to CC.

Not sure, if it ever had gold color.

**Comment by Vodacek** [comment]
Gold cursors are used on map 1 :)
 

---

**Comment by PatrikSamuelTauchim** [comment]
OK I did some tests. On login screen everything is OK and cursor has correct metallic color until characters enters the world, where cursor should be gold. Then it turns dark grey, instead of gold. Changing map to 0 doesnt changing color back to metalic.

Another weird behavour. While switching map, character disappeared completely from game window.
Console shows:
- Unhlandled chat packet ID:179
- Mobile attributes ID:45

**Comment by ZaneDubya** [comment]
Working on this in branch 'hues-fix'. Gold cursor is fixed.

**Comment by robertdeclaux** [comment]
confirmed.

**Comment by ZaneDubya** [comment]
Thank you!

**Comment by PatrikSamuelTauchim** [comment]
Are you sure? Experiencing still the same issues in current master.
- Cursor is grey at map 1 (Trammel)
- World scene is not rendered after changing map

**Comment by ZaneDubya** [comment]
My cursor is gold in Trammel, and grey/gold fringe (unhued) in Felucca.

As for the world scene not rendering - I'm thinking that has something to do with the world data not being loaded.

**Comment by robertdeclaux** [comment]
My cursor was gold at home too but in office it's grey. I'm not sure about home's uo version but i installed visual studio 2013 there (and used 2013 project), here (office) visual studio 2010. Don't know if it makes difference.

**Comment by ZaneDubya** [comment]
With PR #92, map should no longer be black when switching maps.

**Comment by robertdeclaux** [comment]
@ZaneDubya "map should no longer be black when switching maps", tested, working good.

**Comment by ZaneDubya** [comment]
Thank you!
