### ISSUE TITLE
Character created in UltimaXNA cannot speak until restart/relogin

### ISSUE THREAD

**Issue by PatrikSamuelTauchim** [ZaneDubya/UltimaXNA#88]
Just created new character and I cannot speak. Text is not appearing in typing line at all. After client restart, it works fine again.

**Comment by ZaneDubya** [comment]
Ah, I understand what's going on with this: the chat input doesn't reacquire input unless you click on it. Should be a relatively easy fix.

**Comment by ZaneDubya** [comment]
Fixed in 9507dea67c16e89e244f1b18f18386d7f866a6cb.

**Comment by robertdeclaux** [comment]
Confirmed.

**Comment by ZaneDubya** [comment]
Thank you!
