### ISSUE TITLE
Death animation crash

### ISSUE THREAD

**Issue by robertdeclaux** [ZaneDubya/UltimaXNA#91]
While casting energy bolt client crashes but i think it's releated to death animation when horse dies client crashes.

![ekran goruntusu 65](https://cloud.githubusercontent.com/assets/11157985/6959545/f1f084ac-d922-11e4-8687-a6f6a689c992.png)

**Comment by ZaneDubya** [comment]
I believe this was caused by the server sending a PlayDeathAnimation packet before sending the corpse entity to the client. I've added some sanity checking in f747d50162abb3e3d54e09c5bf27f2cdde7b0453, which should keep the client from crashing if this ever happens again.

**Comment by robertdeclaux** [comment]
Working with no problem, confirmed.
![ekran goruntusu 69](https://cloud.githubusercontent.com/assets/11157985/6968091/a5214162-d96c-11e4-908f-7a1f4da8bf59.png)

**Comment by ZaneDubya** [comment]
Excellent! Thank you :)
