### ISSUE TITLE
Please post your HueTest debug screen (Ctrl-D at login).

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#93]
For some reason, UltimaXNA is not huing entities correctly, but only on some clients. I'm trying to figure out why that might be. To test whether the UI SpriteBatch and shader are displaying hues incorrectly, I implemented a HueTest debug screen, which you can display by hitting Ctrl-D at the Login screen.

Would everyone please post a screenshot of your HueTest screen?

**Comment by ZaneDubya** [comment]
Expected output:
![screen shot 2015-04-02 at 1 02 25 pm](https://cloud.githubusercontent.com/assets/7041719/6970037/9bd8eb16-d938-11e4-9b5b-6cb144fbf18d.png)

**Comment by Vodacek** [comment]
![hues](https://cloud.githubusercontent.com/assets/2104849/6970773/07157392-d978-11e4-9280-1acff4fcc32d.png)

**Comment by PatrikSamuelTauchim** [comment]
Actual screenshot from home, where now everything is OK in current master. Hue 1102 on hairs looks just fine.
![hues01](https://cloud.githubusercontent.com/assets/11310587/6970836/b9f6ae60-d980-11e4-8383-a6f925f37c47.jpg)

Tomorrow I will check second VM at job, from where I was reporting issue.

**Comment by ZaneDubya** [comment]
Thank you guys!
@Vodacek Yours is off by two. Which is weird. But weirder still is the fact that the first object (hueid = 0) should be rendered unhued. Hmmm.
@Eskymak Your home is looks good!

**Comment by robertdeclaux** [comment]
Home pc which has no problem with hues. Tomorrow i will upload office pc that has problems.

![ekran goruntusu 19](https://cloud.githubusercontent.com/assets/11157985/6974532/3163d0c0-d99c-11e4-864e-23908d025e37.png)

**Comment by ZaneDubya** [comment]
I've modified the HueTest to show hues 0 and 1 (which are unhued and true black, respectively). @Vodacek, would you post your HueTest again? I'd like to see how the XNA client renders these two hues on your computer.
![screen shot 2015-04-02 at 6 44 30 pm](https://cloud.githubusercontent.com/assets/7041719/6975937/6736c740-d968-11e4-8df5-7647e15bfe74.png)

**Comment by PatrikSamuelTauchim** [comment]
Current master at my machine at work. There is still issue with hues.
![workhues01](https://cloud.githubusercontent.com/assets/11310587/6979011/5a9c9d84-d9e5-11e4-88a1-1adf077239c9.JPG)

**Comment by robertdeclaux** [comment]
My work pc,  still has problems too

![ekran goruntusu 80](https://cloud.githubusercontent.com/assets/11157985/6979083/9258d426-d9e6-11e4-9ae9-b08d081b7311.png)

**Comment by Vodacek** [comment]
![hues](https://cloud.githubusercontent.com/assets/2104849/6979193/353279b0-d9e0-11e4-8171-b9dd2981eea4.png)
I got it, problem is hidden in working PCs :-D

**Comment by PatrikSamuelTauchim** [comment]
I just completely removed UO ML and reinstalled it. Issue persist.
@Vodacek  Yeah, that is punishment for playing at work. :D

**Comment by fdsprod** [comment]
@ZaneDubya Last I check OpenUO Hues worked fine, maybe you can look at this code and spot a difference
https://github.com/jeffboulanger/OpenUO/blob/master/OpenUO.Ultima/Hues/Hues.cs
https://github.com/jeffboulanger/OpenUO/blob/master/OpenUO.Ultima/Hues/Hue.cs

**Comment by ZaneDubya** [comment]
I'm certain the hues are being loaded correctly into memory. I'm certain that they're being written correctly into the hues texture. There seems to be a problem with the huing shader.

On some machines, the shader colors textures with hues at index (hueIndex + 1). On some machines, the shader colors textures with hues at index (hueIndex - 1). I can't imagine why this would be the case.

**Comment by robertdeclaux** [comment]
Home pc working good
![ekran goruntusu 20](https://cloud.githubusercontent.com/assets/11157985/6986418/ba72bae4-da45-11e4-88fa-8698d46ccc90.png)

**Comment by robertdeclaux** [comment]
My home and work outputs are different, is it something good?

**Comment by ZaneDubya** [comment]
I just wish that I had access to a machine that was outputting incorrect hues! Then I could play with the hues until they were correct on both machines.

**Comment by robertdeclaux** [comment]
Just give me 15 minutes, i will take my work pc

**Comment by Vodacek** [comment]
try to set shader version to 3, conditions are handled differently in this shader model

**Comment by ZaneDubya** [comment]
This should be fixed. I believe the problem was with this line of code in the IsometricWorld shader:

`float inHueIndex = ((color.r + color.g + color.b) / (3.0f * 2.0f)) + ((IN.Hue.x % 2.0f) * 0.5f);`

Specifically, I think it had to do with the modulus 2.0f instruction, but I can't be sure.

**Comment by robertdeclaux** [comment]
Working on home PC and work PC together :+1:

**Comment by ZaneDubya** [comment]
Excellent! Can I get one more confirmation from someone else who had the hues-offset error?

**Comment by Vodacek** [comment]
confirmed!

![hue](https://cloud.githubusercontent.com/assets/2104849/6988479/2442f752-da52-11e4-8297-d37aee6ceaba.png)

**Comment by ZaneDubya** [comment]
Awesome! Thanks everyone!

@robertdeclaux thanks for letting me troubleshoot on your computer. :)

**Comment by robertdeclaux** [comment]
looking at @Vodacek 's ss am i the only one who thinks that ultimaxna's render seems better than the original client? Beatiful!!!
@ZaneDubya you are welcome, thanks for fix

**Comment by fdsprod** [comment]
To be fair, the original client uses gdi, a non hardware accelerated engine, ultimaxna obviously uses dx9 :). Not really fair to judge the 2 in the same category.
