### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by naggie** [ZaneDubya/UltimaXNA#94]
As a new user, the first thing I want to see is a screenshot and/or video. Could someone post one in the readme please?

It's brilliant to see an active UO client project -- just when I thought the scene was dead.

**Comment by PatrikSamuelTauchim** [comment]
Hello @naggie,

It is actually a good idea. I am sure, that someone will add some screenshots soon. I can make some tomorrow. It is not a priority, but why not. ;-)

**Comment by naggie** [comment]
Excellent, thanks Eskymak.

BTW, what server do you all use for development/production, given that RunUO has ceased and UOX3 has been asleep for 3 years>

**Comment by fdsprod** [comment]
RunUO is still maintained by Mark here https://github.com/runuo/runuo.

EDIT: By maintained, I mean, he fixes things rarely, but still does from time to time.  I'm guessing if he gets an itch, he would ;)

Apparently our Wiki says UltimaXNA doesnt support RunUO 2.4, but I've had no issues with the ones from github.   I'll have to talk to Zane about this.

**Comment by naggie** [comment]
![image](https://cloud.githubusercontent.com/assets/208440/6973610/d8135774-d983-11e4-86ea-3d3c9440ea9c.png)

Well, given the above message on runo.com I am pleasantly surprised! Great!

**Comment by fdsprod** [comment]
Ya, thats cause Ryan had a falling out with Mark, and Mark left, and he was the last to maintain the code.  So Ryan shut it down because he had no developers (real ones at least).

This is the rumor I've heard anyway....and based on the falling out I had with Ryan, it doesn't surprise me.

**Comment by ZaneDubya** [comment]
Thanks @Eskymak!

@jeffboulanger Not 100% certain, but reasonably positive of this: RunUO 2.4 works so long as it is reading data from a pre-UOP client. But when it reads data from a newer client, it fails to transmit Z values. Please reference Issue #3.

**Comment by robertdeclaux** [comment]
Home pc which has no problem with hues. Tomorrow i will upload office pc that has problems.

![ekran goruntusu 19](https://cloud.githubusercontent.com/assets/11157985/6974514/0374ab94-d99c-11e4-9660-adfe6ddcda22.png)

**Comment by robertdeclaux** [comment]
Some capabilities of ultimaxna as 03.04.2015 on sphere server
https://www.youtube.com/watch?v=gUfpQkLBdzE

**Comment by ZaneDubya** [comment]
@robertdeclaux That's a great video - it shows that the XNA client, in some ways, surpasses the legacy client, and yet also obviously has a ways to go. :)

**Comment by naggie** [comment]
I spy a screenshot! Thanks!
