### ISSUE TITLE
Journal

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#98]
As a player, I want to be able to see a record of chat messages, etc. in my vicinity. The legacy client implements a 'journal scroll' with this functionality.

**Comment by ZaneDubya** [comment]
@robertdeclaux has implemented something very similar to the legacy client's journal in PR #96!

**Comment by ZaneDubya** [comment]
I've merged the pull request. Scrolling still doesn't work - I'll come back and fix that up when I have time - some time next week perhaps. Other cool features that could be added (I'm not working on any of these):
- Hue the text entries! (Could the journal entries keep a hue as well as the text? Or perhaps we could hue based on the type of message?) 
- Include the name of the speaker when the journal entry is a chat message.

**Comment by ZaneDubya** [comment]
Scrolling implemented in PR #120.

**Comment by robertdeclaux** [comment]
Working fantastic :+1:
